In [1]:
print("Hello") 

Hello


In [2]:
import os
from dotenv import load_dotenv
import yfinance as yf
import finnhub

In [17]:
def get_quote(ticker:str)->str:
    finnhub_client = finnhub.Client(api_key=os.environ['FINNHUB_API_KEY'])
    print(finnhub_client.quote(ticker)) 

    quote_data = finnhub_client.quote(ticker)

    return quote_data  



In [18]:
 result = get_quote('AAPL') 

{'c': 291.13, 'd': -4.5, 'dp': -1.5222, 'h': 297.14, 'l': 289.62, 'o': 296.03, 'pc': 295.63, 't': 1781294400}


In [19]:
result['c']

291.13

In [5]:
import finnhub
import os

In [10]:

finnhub_client = finnhub.Client(api_key=os.environ['FINNHUB_API_KEY'])
#print(finnhub_client.company_news('AAPL', _from="2020-06-01", to="2026-06-10"))

quote_data = finnhub_client.company_news("AAPL",_from="2020-06-01", to="2026-06-10") 
print(quote_data)  


[{'category': 'company', 'datetime': 1781133010, 'headline': "Jim Cramer Describes Bitcoin, Gold As 'Bad Money' Getting Dumped For SpaceX — But 'Good Money' Apple And Nvidia Not Spared Either", 'id': 140606589, 'image': 'https://cdn.benzinga.com/files/images/story/2026/06/10/Chinas-Exports-Surge-Despite-US-Shortfal.jpeg?width=2048&height=1536', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'Market commentator and popular media personality\xa0Jim Cramer dubbed Bitcoin (CRYPTO: BTC) and gold as “bad money” on Wednesday, which ', 'url': 'https://finnhub.io/api/news?id=356040073ccebe881a3101322cee4a741fe10a80fc9c4d7cf05661052d67f090'}, {'category': 'company', 'datetime': 1781131800, 'headline': 'Amazon Is the Latest AI Giant to Sign a Blockbuster Deal With This Under-the-Radar Semiconductor Company (Behind Nvidia and Meta)', 'id': 140600825, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'This company i

[{'category': 'company', 'datetime': 1781133010, 'headline': "Jim Cramer Describes Bitcoin, Gold As 'Bad Money' Getting Dumped For SpaceX — But 'Good Money' Apple And Nvidia Not Spared Either", 'id': 140606589, 'image': 'https://cdn.benzinga.com/files/images/story/2026/06/10/Chinas-Exports-Surge-Despite-US-Shortfal.jpeg?width=2048&height=1536', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'Market commentator and popular media personality\xa0Jim Cramer dubbed Bitcoin (CRYPTO: BTC) and gold as “bad money” on Wednesday, which ', 'url': 'https://finnhub.io/api/news?id=356040073ccebe881a3101322cee4a741fe10a80fc9c4d7cf05661052d67f090'}, {'category': 'company', 'datetime': 1781131800, 'headline': 'Amazon Is the Latest AI Giant to Sign a Blockbuster Deal With This Under-the-Radar Semiconductor Company (Behind Nvidia and Meta)', 'id': 140600825, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'This company is applying its 175 years of experience to transform the artificial intelligence industry.', 'url': 'https://finnhub.io/api/news?id=e2cf0352e3c6687e1c9923cb35ef15dac3af9ef0a24b51100f900d9fe158ae8a'}, {'category': 'company', 'datetime': 1781129220, 'headline': 'Morgan Stanley revamps Apple stock target after key event', 'id': 140600831, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple (AAPL) has spent the bulk of the past couple of years trying to convince investors it has not fallen behind in the relentless AI race. Morgan Stanley buys that story. According to TheFly, the firm reset its price target on Apple stock after WWDC 2026, saying the event gave investors a sharper ...', 'url': 'https://finnhub.io/api/news?id=cc2850a828e689c3aed28bf6131d14dc74ed717fcce9de3554eb8e63471e51aa'}, {'category': 'company', 'datetime': 1781126851, 'headline': "CNBC Daily Open: Trump expresses 'love' for inflation print and anger at Iran", 'id': 140608151, 'image': 'https://image.cnbcfm.com/api/v1/image/108319909-1781124544975-gettyimages-2280950709-mms27734_nzaahxva.jpeg?v=1781124703&w=1920&h=1080', 'related': 'AAPL', 'source': 'CNBC', 'summary': 'U.S. inflation reached a three-year high of 4.2%, with Trump arguing that ending the war will resolve both the conflict and rising prices.', 'url': 'https://finnhub.io/api/news?id=efbdcba965a53d21a9e6616f69d5543e6b02ac22b9788866c07fa42bbe94eb82'}, {'category': 'company', 'datetime': 1781126403, 'headline': 'Stock Market Today, June 10: Super Micro Computer, Nvidia, Micron Fall as Risk-Off Mood Intensifies', 'id': 140599152, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'AI hardware shares slide as investors digest Super Micro’s massive stock sale, hot inflation, and rising tensions in the Gulf, today, June 10, 2026.', 'url': 'https://finnhub.io/api/news?id=f848519ad1389d4f9661758b1d5e37d2cdc045ed23156e2cd531fbdd148645fe'}, {'category': 'company', 'datetime': 1781124600, 'headline': 'Apple Got It Right This Time', 'id': 140600836, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Investors are misreading Apple’s latest AI announcement. The updates to Apple Intelligence and Siri are good enough for customers—and the stock.', 'url': 'https://finnhub.io/api/news?id=6e37ea94c971080046f6fa89239bceb84f11f1ca5a9f5b6ae955b7888b77fff0'}, {'category': 'company', 'datetime': 1781123897, 'headline': 'Stocks Settle Sharply Lower on Escalating Middle East Tensions', 'id': 140603008, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'The S&P 500 Index ($SPX ) (SPY ) on Wednesday closed down -1.62%, the Dow Jones Industrial Average ($DOWI ) (DIA ) closed down -1.87%, and the Nasdaq 100 Index ($IUXX ) (QQQ ) closed down -1.98%. June E-mini S&P futures (ESM26 ) fell -1.62%, and June E-mini Nasdaq futures...', 'url': 'https://finnhub.io/api/news?id=a1805e474a50fb022c497c16177c1536d8ec613890bf5842aa370e11db9de9a7'}, {'category': 'company', 'datetime': 1781123473, 'headline': 'Apple Spent Billions Chasing A Self-Driving Car, Then Walked Away—Waymo Now Bought The Test Site For $220 Million', 'id': 140599170, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Alphabet Inc.-backed Waymo has reportedly acquired Apple Inc.‘s self-driving proving facility in Arizona for $220 million. Waymo Acquires Apple Facility On Monday, the Phoenix Business Journal first reported that Waymo acquired the property from Delaware-based Route 14 Investment Partners LLC,...', 'url': 'https://finnhub.io/api/news?id=65119bdd681caf77ef57914801fdacf5a4bb4dbcf089097ef3c616e5ebe1cfe4'}, {'category': 'company', 'datetime': 1781123100, 'headline': 'Apple Just Introduced Next-Generation Siri AI at WWDC. Why That Might Not Be Enough to Give AAPL Stock a Boost.', 'id': 140603007, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'While AI-driven revenue opportunities may take time to materialize, solid iPhone demand and strength in the Services segment will support Apple’s growth.', 'url': 'https://finnhub.io/api/news?id=8a9f1175ccf598798f78acf989657b19ee200ef98ba205e08fa408e1f8b897d8'}, {'category': 'company', 'datetime': 1781120435, 'headline': 'Jim Cramer talks how SpaceX IPO is hitting the markets already', 'id': 140608153, 'image': 'https://image.cnbcfm.com/api/v1/image/108320001-4ED3-MM-F-BLOCK-061026.jpg?v=1781133481&w=1920&h=1080', 'related': 'AAPL', 'source': 'CNBC', 'summary': "'Mad Money' host Jim Cramer looks at how SpaceX's upcoming IPO is hurting markets.", 'url': 'https://finnhub.io/api/news?id=1303f82a08bcd002c7406a198bdfbc1631ea89f72821a5b608be0d315e358d5c'}, {'category': 'company', 'datetime': 1781120172, 'headline': 'Apple Bets Big on Siri AI. Investors Aren’t Buying It.', 'id': 140597334, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Wall Street punished Apple stock this week after WWDC 2026 revealed an AI-powered Siri reboot that felt more like ecosystem lock-in than innovation.', 'url': 'https://finnhub.io/api/news?id=ad0fe46a96c4cb73abadd4bb1ff2f9091a0c503ec2c06df57a13814b8ae0ee6c'}, {'category': 'company', 'datetime': 1781118602, 'headline': 'Which dow jones stocks are moving on Wednesday?', 'id': 140596961, 'image': 'https://www.chartmill.com/images/uploads/CM_Top_Movers_Small_free_2b4ff2fc22.webp', 'related': 'AAPL', 'source': 'ChartMill', 'summary': "Stay updated with the movements of the dow jones index one hour before the close of the markets on Wednesday. Discover which stocks are leading as top gainers and losers in today's session.", 'url': 'https://finnhub.io/api/news?id=053fea32457bdc9084abf1e7ae1bf00fdcae9db1ccd65bd722c43edaaedad38c'}, {'category': 'company', 'datetime': 1781117945, 'headline': 'XMAG vs. MAGS: Betting Against or All-In on the Magnificent 7?', 'id': 140597329, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'The Defiance Large Cap ex-Mag 7 ETF (NASDAQ:XMAG) and the Roundhill Magnificent Seven ETF (NASDAQ:MAGS) are photographic negatives of one another. MAGS holds only the seven mega-caps driving the AI cycle, while XMAG holds the S&P 500 with those same seven names surgically removed. Owning one is the inverse of owning the other, and 2026 ... XMAG vs. MAGS: Betting Against or All-In on the Magnificent 7?', 'url': 'https://finnhub.io/api/news?id=efedfb49a9c64b277831f459f32bb44ee6fce06ad91c1afe928fc42bd1ae0fbf'}, {'category': 'company', 'datetime': 1781117407, 'headline': 'RSP vs. SPY: Does Equal Weight Beat the Cap-Weighted S&P 500?', 'id': 140597336, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'The choice between the Invesco S&P 500 Equal Weight ETF (NYSEARCA:RSP) and the SPDR S&P 500 ETF Trust (NYSEARCA:SPY) looks trivial on a fund screener. You have the same 500 companies, both tracking the S&P 500, and both are cheap. The weighting scheme is the entire story, as SPY’s cap-weighted holdings allocate 7.58% of the ... RSP vs. SPY: Does Equal Weight Beat the Cap-Weighted S&P 500?', 'url': 'https://finnhub.io/api/news?id=be39dde876d271e652a29d48d11632d2b8dadb1dc2d1847fd12119671d50e427'}, {'category': 'company', 'datetime': 1781115624, 'headline': 'QQQ vs. VGT: The Best Way to Own Big Tech?', 'id': 140597337, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'The Invesco QQQ Trust (NASDAQ:QQQ) and the Vanguard Information Technology ETF (NYSEARCA:VGT) are often shoved into the same “own Big Tech” bucket, but they answer different questions. QQQ tracks the Nasdaq-100, a listing-based index that is growth-heavy. VGT tracks the MSCI US Investable Market Information Technology 25/50 Index, a pure GICS sector fund. That distinction ... QQQ vs. VGT: The Best Way to Own Big Tech?', 'url': 'https://finnhub.io/api/news?id=5a6b2cdc99ce98ff93f142ec9c503de46859fa74f3f8792d22464b9121695dd4'}, {'category': 'company', 'datetime': 1781114700, 'headline': 'Which S&P500 stocks are the most active on Wednesday?', 'id': 140596171, 'image': 'https://www.chartmill.com/images/uploads/CM_Most_Active_Stocks_Small_free_fec0650b7f.webp', 'related': 'AAPL', 'source': 'ChartMill', 'summary': "Looking for the most active S&P500 stocks in today's session? Join us as we dive into the US markets on Wednesday and discover the stocks that are dominating the trading activity and setting the pace for the market.", 'url': 'https://finnhub.io/api/news?id=e38c3ba02d10e62969360962168714b3e60ed6130fa653eaf660fadc0a3c58b2'}, {'category': 'company', 'datetime': 1781114401, 'headline': "CNBC Sport: MLS Commissioner Don Garber on his ideal World Cup and why Apple's 'Season Pass' strategy didn't work", 'id': 140608154, 'image': 'https://image.cnbcfm.com/api/v1/image/108319789-Garber_Carbon-Still002.png?v=1781114788&w=1920&h=1080', 'related': 'AAPL', 'source': 'CNBC', 'summary': "CNBC's Alex Sherman sits down with Don Garber, Major League Soccer commissioner.", 'url': 'https://finnhub.io/api/news?id=e3cee38bedc5d74e51cf592253c88b7c1e15341ef0871bd792a105cbfeb7dc56'}, {'category': 'company', 'datetime': 1781113974, 'headline': 'If Apple Stock Stabilizes, This Iron Condor Sets Up A 35% Return In Five Weeks', 'id': 140597338, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "Apple  stock has slumped in recent days\xa0but is showing significant positive gamma, which can be a scenario that leads to a more stable stock price.  On the stock chart, Apple has strong support around 270-280 and resistance around 315.  Let's look at how we might set up an iron condor on Apple stock.", 'url': 'https://finnhub.io/api/news?id=d850b87e17eafb5f6ad614b633eb002b591fb82cb6d6ab5c27125b66b5ab37f7'}, {'category': 'company', 'datetime': 1781110339, 'headline': 'TSMC Sales Jump as AI Demand Holds Strong', 'id': 140595638, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'AI Chip Demand Keeps Advanced Manufacturing Momentum Strong', 'url': 'https://finnhub.io/api/news?id=59c6bce1bc2ac6ef73e9e3797fd9b92f6c440e9c6809c0d927264a21d77e9255'}, {'category': 'company', 'datetime': 1781109853, 'headline': 'Apple Unveils AI Reset As Siri Gets Major Upgrade', 'id': 140595649, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "Apple's WWDC update adds Siri AI, Gemini-based architecture and faster software features across its ecosystem.", 'url': 'https://finnhub.io/api/news?id=c7be5fdde3c758b5d6bb1c7d1381aca9679e2e923212f1a293486c31651bdadb'}, {'category': 'company', 'datetime': 1781109051, 'headline': "Apple Reveals Siri AI, But Gene Munster Asks The Key Question: 'Do They Have The AI Chops To Deliver?'", 'id': 140595650, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple Inc.’s long-awaited unveiling of Siri AI at its Worldwide Developers Conference (WWDC) drew mixed reactions from Wall Street, with some analysts applauding the vision while others questioned whether the company can deliver the technology on the timeline investors expect....', 'url': 'https://finnhub.io/api/news?id=d45d087c2bd5ed5008434b772b508db01a96d9ed85774b34ee47d9a0308bd0ca'}, {'category': 'company', 'datetime': 1781108970, 'headline': 'CPI Saves Market; China-Taiwan Tensions Hurt Semis-Momo Crowd Buys the Dip; Iran Truce Looks More Fragile', 'id': 140598718, 'image': 'https://cdn.benzinga.com/files/images/story/2026/06/10/Hawthorne-LA-CoSpaceX-Headquarters-locat.jpeg?width=2048&height=1536', 'related': 'AAPL', 'source': 'Benzinga', 'summary': '\n\n\n\nCPI Saves Stock Market\n\n\n', 'url': 'https://finnhub.io/api/news?id=fea2834fde1950eff2c8ef098805253dd79d1a2bcb06a4641e536c0aa3f43860'}, {'category': 'company', 'datetime': 1781108875, 'headline': 'Weirdly, the iPhone Might Be About to Become a Huge Drag on Apple’s Stock Price — or Maybe Not?', 'id': 140595651, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'There’s been a lot of buzz surrounding Apple (NASDAQ:AAPL) after its big WWDC week. The latest Siri AI innovations look quite impressive, but, of course, if we’ve learned anything from the initial rollout of Apple Intelligence, it’s that we should reserve judgment until we’ve actually had a chance to test out the waters. Indeed, iOS ... Weirdly, the iPhone Might Be About to Become a Huge Drag on Apple’s Stock Price — or Maybe Not?', 'url': 'https://finnhub.io/api/news?id=6eacde21ee041f8612af69ce07809ca6ceb3418f1a5ef9d1cfa8e5834b7c8d0e'}, {'category': 'company', 'datetime': 1781107365, 'headline': 'Volkswagen Reaffirms ESG Targets, Bets on Circular Economy to Cut Costs', 'id': 140595652, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Volkswagen (ETR:VOW3) reaffirmed its sustainability targets and outlined new circular economy initiatives during its eighth sustainability conference, with executives saying ESG remains embedded in the company’s broader strategy despite a more difficult economic backdrop. Dirk Voeste, who presented', 'url': 'https://finnhub.io/api/news?id=273bff8287673e6accd3595cf418b9710be5f5f2a25e73ef99467c032f7970d6'}, {'category': 'company', 'datetime': 1781106798, 'headline': 'CNBC TechCheck Evening Edition: June 10, 2026', 'id': 140608155, 'image': 'https://image.cnbcfm.com/api/v1/image/108319865-P-TechCheck_SPONSORED_SIGALOS_061026-CC.jpg?v=1781121056&w=1920&h=1080', 'related': 'AAPL', 'source': 'CNBC', 'summary': "CNBC's TechCheck brings you the latest in tech news from CNBC's 1 Market in the heart of San Francisco.", 'url': 'https://finnhub.io/api/news?id=9a1a107a7cb29a656d650af984f42b9908844adbe61a5fb4df7319c2b75d6302'}, {'category': 'company', 'datetime': 1781105931, 'headline': 'Jim Cramer Notes “Of the Big-Cap Stocks, Apple Had Been the Cleanest Story”', 'id': 140593783, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple Inc. (NASDAQ:AAPL) was among the stocks Jim Cramer discussed during Mad Money, as he highlighted a difficult backdrop for stocks. Cramer highlighted the recent pullback in the stock, as he stated: That pullback in the stock of Apple today. Of the big-cap stocks, Apple had been the cleanest story. It didn’t have to spend […]', 'url': 'https://finnhub.io/api/news?id=dfa9cb378421afa9b55ca24051fc1fde268b50024ba22781133553b0c4797e87'}, {'category': 'company', 'datetime': 1781103954, 'headline': 'Is Microsoft Stock Too Cheap To Ignore?', 'id': 140593784, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "Microsoft (MSFT) stock is at an interesting point right now. If you bet on it, you are betting on a company that's growing reasonably, is sustaining good cash flow and margin, has a low-debt to market cap structure, and is relatively cheaply valued. But is that enough.", 'url': 'https://finnhub.io/api/news?id=5e2378a736be82b725bc8fc1269c09434a6c2c493c85aef20e09d091bb4dc521'}, {'category': 'company', 'datetime': 1781103600, 'headline': 'M2M Healthcare Market Size to Reach USD 28.77 Billion by 2031 Driven by Connected Healthcare and Remote Monitoring Adoption | Valuates Reports', 'id': 140593785, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'M2M Healthcare Market Size to Reach USD 28.77 Billion by 2031 Driven by Connected Healthcare and Remote Monitoring Adoption | Valuates Reports', 'url': 'https://finnhub.io/api/news?id=5ef9742bfe19914cda55b0da8f9ad44d611e2bbecc87f3258ec8694a9127f8ed'}, {'category': 'company', 'datetime': 1781099776, 'headline': 'Apple’s Next Chapter: AI Innovation and Leadership Change Signal Upside', 'id': 140593786, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple’s (NASDAQ:AAPL) stock hit a fresh all-time high around $317.40 in late May, then slid 7.82% in a week as investors digested CEO succession news, valuation concerns, and softer sentiment. With Tim Cook delivering his final WWDC keynote and Siri AI getting its overhaul, the next 12 months are pivotal. Here is what our model ... Apple’s Next Chapter: AI Innovation and Leadership Change Signal Upside', 'url': 'https://finnhub.io/api/news?id=03eddcdcfc5bf762ef004f6aaffa5cbdb5558a632db8f0a6f5ad840e64d67079'}, {'category': 'company', 'datetime': 1781099750, 'headline': "Robinhood's JB Mackenzie: Perpetual futures is a great opportunity for us", 'id': 140608156, 'image': 'https://image.cnbcfm.com/api/v1/image/108319779-17811136591781113656-46463933446-1080pnbcnews.jpg?v=1781113658&w=1920&h=1080', 'related': 'AAPL', 'source': 'CNBC', 'summary': "JB Mackenzie, Robinhood vice president, joins 'The Exchange' to discuss the latest demand for prediction markets, perpetual futures and much more.", 'url': 'https://finnhub.io/api/news?id=30622723acb645f934e685496eefdacd18ba690288ff43261f89c25353352579'}, {'category': 'company', 'datetime': 1781099654, 'headline': "Apple's AI Push Deepens Alphabet Dependency", 'id': 140592709, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "Apple's upgraded Siri will rely partly on Google AI infrastructure as privacy and regulatory questions grow.", 'url': 'https://finnhub.io/api/news?id=a50a4a1671ab8a72b6d1d2721c21f3b90ea6dff5f915891006ec019ee4bc906f'}, {'category': 'company', 'datetime': 1781099021, 'headline': 'AI Boom Sends TSMC Sales Soaring 30% as Chip Appetite Explodes', 'id': 140592690, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'TSMC Delivers Massive Revenue Jump as Nvidia, Apple Demand Ramps Up', 'url': 'https://finnhub.io/api/news?id=75483cd85a921eae0dabdd1c0d80266bac97b7971de1d6aa6b2a7f793dd08052'}, {'category': 'company', 'datetime': 1781097480, 'headline': "The World's Most Important Chipmaker Has Fantastic News for Artificial Intelligence (AI) Stock Investors", 'id': 140592698, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "TSMC's CEO believes the semiconductor market will remain undersupplied due to booming demand for AI chips.", 'url': 'https://finnhub.io/api/news?id=fa777decd6233f7bf1538bcac51a65ddc6e4cc027922c72253fe926e4a8ea37e'}, {'category': 'company', 'datetime': 1781096884, 'headline': 'Apple (AAPL) Declined Defies Strong Fundamentals', 'id': 140592712, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'The London Company, an investment management company, released its first-quarter 2026 investor letter for its “The London Company Income Equity Strategy”. A copy of the letter is available to download here. In early 2026, US equities declined, with the Russell 3000 falling 4% and the S&P posting losses. The year began positively on a broad […]', 'url': 'https://finnhub.io/api/news?id=7a7ca43bcf0341ce8917c1035a5193824bdf8d2ecfb1012cea8c83482de76263'}, {'category': 'company', 'datetime': 1781096451, 'headline': 'Telegram’s TON Rebrand Gets Apple Boost as Durov Expands the Ecosystem', 'id': 140592713, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "Pavel Durov launches a native Telegram Apple Watch app as TON's token rebrands to GRAM on June 15 with no swap required.", 'url': 'https://finnhub.io/api/news?id=df5ff9370ab3471edaba7859fd18ceb30af2bb2c4d694c80b7d0e0bf88976376'}, {'category': 'company', 'datetime': 1781095718, 'headline': 'Chase unveils massive Sapphire Preferred overhaul: Enhanced rewards, new perks and a crushing transfer partner change', 'id': 140594844, 'image': 'https://image.cnbcfm.com/api/v1/image/108319621-1781106134884-gettyimages-2267173838-2202_2026-ex-familyhomenorth0810.jpeg?v=1781106141&w=1920&h=1080', 'related': 'AAPL', 'source': 'CNBC', 'summary': "The Chase Sapphire Preferred is getting a big update. Here's what you need to know about the good and the bad changes happening soon.", 'url': 'https://finnhub.io/api/news?id=77ae389caa2078392059f1184d437c9aa75bc365a5d2a56e7f10f087c7b7dfad'}, {'category': 'company', 'datetime': 1781095674, 'headline': 'Apple Might Haven Taken Aim at OpenAI with New Announcement. There’s Only One Problem.', 'id': 140592714, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple (NASDAQ:AAPL) stock has not reacted all too positively amid WWDC 2026. Undoubtedly, that’s not because the presentation disappointed. There were ample AI innovations under the hood, but, in terms of the surprise factor, not much wasn’t on the bingo cards of investors going into the big week. Siri AI is finally here, and the ... Apple Might Haven Taken Aim at OpenAI with New Announcement. There’s Only One Problem.', 'url': 'https://finnhub.io/api/news?id=7004c39d094d61d33360f90a415b87efa85b0d8bf2b8bd746237917505315560'}, {'category': 'company', 'datetime': 1781095232, 'headline': 'Why One AI Giant Is Paying ~2.2X per GPU More Than What Anthropic Pays SpaceX', 'id': 140592705, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Just in time for that big SpaceX (SPCX) IPO, the firm announced that Alphabet‘s (NASDAQ:GOOG) Google has inked a $920 million per-month deal for AI compute that’ll run through the middle of 2029. Undoubtedly, the deal entails 110,000 worth of Nvidia (NASDAQ:NVDA) GPUs, which might seem like a worse deal than Anthropic got when it ... Why One AI Giant Is Paying ~2.2X per GPU More Than What Anthropic Pays SpaceX', 'url': 'https://finnhub.io/api/news?id=a5f4131191aaae577109a25fb56c217bf32c2f26c89a32957de2e286f6e00498'}, {'category': 'company', 'datetime': 1781094120, 'headline': 'Leading Public AI Company RLTR Supports No Data Center in Monterey Park and Calls for AI Progress Without Massive Data Center Expansion', 'id': 140592716, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'RI’s Proprietary Fully Distributed, Infrastructure-Light Architecture Signals a Break from Traditional AI Models as Microsoft, NVIDIA, Alphabet, Meta Platforms, Palantir, OpenAI, Anthropic, xAI, Luma AI, Amazon, and Apple Continue Advancing Capital-Intensive AI Systems RI - Everything. Bothell, WA, June 10, 2026 (GLOBE NEWSWIRE) -- ReelTime Media, Inc. (OTCID:RLTR) today announced its support for No Data Center in Monterey Park No Data Center in Monterey Park! and the community-led effort that h', 'url': 'https://finnhub.io/api/news?id=add96f8abc71280f3afe7fc5f972f01cf3f0657d259091163f81ba287e44cfa3'}, {'category': 'company', 'datetime': 1781093321, 'headline': 'Apple EU AI Delay Puts Spotlight On Valuation And Growth Expectations', 'id': 140592717, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple (NasdaqGS:AAPL) is delaying the launch of its new Siri AI and Apple Intelligence features in the European Union. The initial rollout will focus on the U.S. and select other markets while Apple works to address EU regulatory requirements, including the Digital Markets Act. The decision limits access to these next-generation AI tools for hundreds of millions of European users at launch. For readers following Apple, this development comes right after the company highlighted a rebuilt...', 'url': 'https://finnhub.io/api/news?id=8b25828a16faafa789281868e98ab7b5b32d468fd3e004dd7836581c9d1beb9d'}, {'category': 'company', 'datetime': 1781092871, 'headline': 'AI Infrastructure Short-Circuits But Now Sparks Not One, But Two Buy Points', 'id': 140592718, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Riding demand for AI data centers, AI infrastructure leader Amphenol looks to connect with a fresh breakout.', 'url': 'https://finnhub.io/api/news?id=7610c8d3daf3b2242a0f367f8d33e318d85cb3091e36bd3db71226431b293fc5'}, {'category': 'company', 'datetime': 1781092197, 'headline': 'Inflation Is Back Above 4%: The ETF Strategy Wall Street May Revisit As Fed Risks Drift Higher', 'id': 140595342, 'image': 'https://cdn.benzinga.com/files/images/story/2026/06/10/Inflation-Word-On-Wooden-Cube-With-With-.jpeg?width=2048&height=1536', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'U.S. inflation topped 4% for the first time since 2023, raising questions about Fed rate cuts. Here&#39;s why dividend and quality ETFs deserve attention now.', 'url': 'https://finnhub.io/api/news?id=f6add7d329236b9bedb431797474dea891daed61ba7b438f9dea1348fbc6d1da'}, {'category': 'company', 'datetime': 1781090125, 'headline': 'Forget VOO: Fidelity’s Tech ETF Is Up 29% While the Broad Market Lags', 'id': 140591934, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'A $10,000 position in Fidelity MSCI Information Technology Index ETF (NYSEARCA:FTEC) on the last trading day of 2025 was worth about $12,480 by the close on June 8, 2026, a gain that arrived in roughly five months while the broad market did something far more modest. The same $10,000 parked in Vanguard S&P 500 ETF ... Forget VOO: Fidelity’s Tech ETF Is Up 29% While the Broad Market Lags', 'url': 'https://finnhub.io/api/news?id=f1ad4ad5c95c4e06065ea80bae1378cdee69b15df840bb7a3aa756358460094e'}, {'category': 'company', 'datetime': 1781087495, 'headline': 'A glossary to help understand what happens in an initial public offering', 'id': 140591952, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "Anyone following SpaceX's plans to sell shares to the public is likely to hear terms thrown around that describe steps and components of an initial public offering.  It is the first time a company's value will be determined by a public market.  For example, Apple is traded as “AAPL” on the Nasdaq and Macy's is traded as “M” on the New York Stock Exchange.", 'url': 'https://finnhub.io/api/news?id=3269b97296e51c078270fd83126bad7cc5664dcafaeb0bfe68e9c1b3e959e677'}, {'category': 'company', 'datetime': 1781087341, 'headline': 'XEL Energy: Wildfires And Surging Electrical Demand', 'id': 140593227, 'image': 'https://static.seekingalpha.com/cdn/s3/uploads/getty_images/2247820886/image_2247820886.jpg?io=getty-c-w1536', 'related': 'AAPL', 'source': 'SeekingAlpha', 'summary': 'Xcel Energy (XEL) outlook: rising U.S. power demand, $60B capex, EPS growth and valuation upsideâ\x80\x94plus wildfire and rate-hike risks.', 'url': 'https://finnhub.io/api/news?id=37072c82036c875bfb9c579c562131075d5d62c99f9dcd087abd9af5244d4968'}, {'category': 'company', 'datetime': 1781085770, 'headline': 'AT&T Rolls Out 24-Hour Unlimited Day Pass Wireless Data Connection For Eligible iPad Users In U.S. For A Daily $3 Flat Rate', 'id': 140599900, 'image': '', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'AT&amp;T launched\xa0Unlimited Day Pass, a 24-hour unlimited wireless data1 connection for eligible U.S. iPad users, including non-AT&amp;T customers, for a daily2 *$3 flat rate — with no contracts, subscriptions', 'url': 'https://finnhub.io/api/news?id=6ba103313561141442aae5c1748ceb7b17c5e121660ea0c0ca7dffd82a6b5843'}, {'category': 'company', 'datetime': 1781084554, 'headline': 'Jim Cramer Says “For the Longest Time, We Questioned Apple’s Ambitions in the AI Space”', 'id': 140591372, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple Inc. (NASDAQ:AAPL) was among the stocks Jim Cramer discussed on Mad Money, along with the recent sell-off in the market. Cramer believes “Siri’s going to get smart,” as he stated: For now, let’s just say you’re looking at a market that’s hostage to interest rates and high oil, coupled with a monster amount of […]', 'url': 'https://finnhub.io/api/news?id=b8174fbb6c5d028f09e9b218e910418e195299b78dd097b6a26942ad1b3f0d65'}, {'category': 'company', 'datetime': 1781077500, 'headline': 'QDVO: Attractive Yield, But Dividend Growth Is The Real Story', 'id': 140591900, 'image': 'https://static.seekingalpha.com/cdn/s3/uploads/getty_images/2242190421/image_2242190421.jpg?io=getty-c-w1536', 'related': 'AAPL', 'source': 'SeekingAlpha', 'summary': 'QDVO ETF blends growth and income with tactical covered calls, double-digit yields, and tax-efficient ROC. Click here to read more about the fund.', 'url': 'https://finnhub.io/api/news?id=0aa5238fa91b8ad99ccaaf00a4b061ae65ec025dc020b112c828b4495163c540'}, {'category': 'company', 'datetime': 1781073791, 'headline': "Apple's AI Reveal Hands An Unexpected Win To Google, NVIDIA", 'id': 140594625, 'image': 'https://cdn.benzinga.com/files/images/story/2026/06/10/Bangkok--Thailand---July-30--2019--Siri-.jpeg?width=2048&height=1536', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'Alphabet emerges as a surprise WWDC winner as Apple relies on Google Cloud and NVIDIA chips to power heavy AI workloads.', 'url': 'https://finnhub.io/api/news?id=dd1f2e1e8f190c8dc550eaebcdd34f487a49f10f19a015e860d4380ab8442bec'}, {'category': 'company', 'datetime': 1781071136, 'headline': 'Performance Comparison: Apple And Competitors In Technology Hardware, Storage &amp; Peripherals Industry', 'id': 140600344, 'image': 'https://cdn.benzinga.com/files/images/story/2025/11/06/earnings_preview_11.jpg?width=2048&height=1536', 'related': 'AAPL', 'source': 'Benzinga', 'summary': ' ', 'url': 'https://finnhub.io/api/news?id=7af606239c25ee9b4a28c59a00c69bb1ef0b4095219d9f14b5406aceeafbee06'}, {'category': 'company', 'datetime': 1781065302, 'headline': 'Telegram Returns To Apple Watch With Native App Supporting Messages, GIFs And Video Playback', 'id': 140600345, 'image': 'https://cdn.benzinga.com/files/images/story/2026/06/10/Telegrams-Pavel-Durov-Reveals-Secret-To-.jpeg?width=2048&height=1536', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'Telegram has launched a native Apple Watch app, bringing back wrist-based messaging, voice notes, and media features, Pavel Durov announced.', 'url': 'https://finnhub.io/api/news?id=b57a00d5308072eefe7b122df6f4300b9bc67a988b513cbf1fc74f45beabae95'}, {'category': 'company', 'datetime': 1781065061, 'headline': 'Apple-Nvidia Friends Again? Nvidia Says Its Chips In Google Cloud Are Powering Apple Intelligence', 'id': 140590451, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple shifted to AMD’s graphics chips around 2015 after encountering reliability issues with some Nvidia GPUs, alongside broader disagreements over product design, technology roadmaps, and licensing.', 'url': 'https://finnhub.io/api/news?id=5556e28f16a96a830a60a44d7b5521982f6ef86f57ee40e27c10907fcbfed4b4'}, {'category': 'company', 'datetime': 1781063460, 'headline': "Forget the AI Headlines: Apple's First Foldable iPhone Could Be the Stock's Biggest Catalyst in Years", 'id': 140590452, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "The tech giant's next hardware cycle, not its new Siri AI, may be the bigger story heading into the fall.", 'url': 'https://finnhub.io/api/news?id=f65106982845f9301410525762fe9695987990ec9f22245ea51b21ad0fc0f6f9'}, {'category': 'company', 'datetime': 1781058780, 'headline': 'Bank of America sends clear message on Apple stock after key event', 'id': 140589922, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "Apple shares fell 3.64% on June 9 after the company's annual Worldwide Developers Conference (WWDC) failed to deliver the major surprises some investors were hoping for. WWDC is Apple's important event of the year, where the company usually unveils updates to iOS, macOS, iPadOS, and other products. ...", 'url': 'https://finnhub.io/api/news?id=9849cf14925230eca4b5371e2965bca2806542cc0b9b7baaf686d595e05184c6'}, {'category': 'company', 'datetime': 1781058134, 'headline': 'Why Apple (AAPL) Shares Are Sliding Today', 'id': 140589923, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Shares of iPhone and iPad maker Apple (NASDAQ:AAPL) fell 3.3% in the afternoon session after the WWDC keynote did not deliver the kind of AI leap many investors had been positioning for.', 'url': 'https://finnhub.io/api/news?id=14f0e64fe824438fc92b1aa5453e14cbd0ed37814867160a36c01546a60f9d0c'}, {'category': 'company', 'datetime': 1781057779, 'headline': 'SoftBank sinks over 8% as global tech stocks tumble, tracking Wall Street losses', 'id': 140594846, 'image': 'https://image.cnbcfm.com/api/v1/image/108217809-17616605332025-10-28t133419z_1627962344_rc2v31a6hnxm_rtrmadp_0_tech-substrate.jpeg?v=1761660590&w=1920&h=1080', 'related': 'AAPL', 'source': 'CNBC', 'summary': 'Semiconductor and technology stocks fell on Wednesday, tracking overnight losses on Wall Street.', 'url': 'https://finnhub.io/api/news?id=e32e0e2797272ff50b96328501ad5453761eebeed98f2497fb0e273f2254ab2b'}, {'category': 'company', 'datetime': 1781053928, 'headline': 'Tech Buckles Again, An Apache Goes Down Over Hormuz, And Oracle Takes The Stand', 'id': 140590995, 'image': 'https://www.chartmill.com/images/uploads/THUMBNAILS_CHARTMILL_1000_528_11_afa9b21d7b.webp', 'related': 'AAPL', 'source': 'ChartMill', 'summary': 'The Nasdaq spent the day on a rollercoaster and still finished a percent lower. Chips sold off again, Apple closed below water for a second straight session, oil fell despite a downed US helicopter over Hormuz, and Oracle reports tonight.', 'url': 'https://finnhub.io/api/news?id=462fcf65f91679d1fd8216839fa676d3a3cc94f2705a42c67f52467cb4257a3c'}, {'category': 'company', 'datetime': 1781047802, 'headline': 'Intel Stock Has Risen Sixfold from Its 2025 Lows, but Don’t Expect a Dividend Yet', 'id': 140590453, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "INTC's reversal of fortunes has been a huge boon to investors, but with capex spending still expected to remain high and customers' cash slow to accumulate, don't expect Intel to reinstate its dividend anytime soon.", 'url': 'https://finnhub.io/api/news?id=b8d4a5112663cd24634939e3d39a95e6d72da878ee3b17d31ad2b97a0610366d'}, {'category': 'company', 'datetime': 1781046000, 'headline': "Markets Edge Higher As Friday's Rout Recovery Continues", 'id': 140589674, 'image': 'https://static.seekingalpha.com/cdn/s3/uploads/getty_images/2223715503/image_2223715503.jpg?io=getty-c-w1536', 'related': 'AAPL', 'source': 'SeekingAlpha', 'summary': 'The AI trade is still alive and kicking. Oil prices fall below $90 a barrel. OpenAI jumps on the IPO bandwagon.', 'url': 'https://finnhub.io/api/news?id=8671174ed5bcc4b782ebed74704204a02e1762cf0c9f239a058ffe1bbfffacb5'}, {'category': 'company', 'datetime': 1781043960, 'headline': 'Apple Will Run Advanced AI Model on Nvidia GPUs via Google Cloud, Ditching Private Infrastructure', 'id': 140588200, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple (NASDAQ:AAPL), the most vertically integrated company in tech, is turning to Nvidia and Google Cloud to power its most advanced AI workloads. According to CNBC’s MacKenzie Sigalos, Apple software chief Craig Federighi confirmed that the company’s new frontier language model, FM Cloud Pro, will run on Nvidia GPUs hosted in Google Cloud for agentic ... Apple Will Run Advanced AI Model on Nvidia GPUs via Google Cloud, Ditching Private Infrastructure', 'url': 'https://finnhub.io/api/news?id=cc12af87a5b85d6fe4ec0d2e74fad694d929a4b2b57912d81dd677ea4064aef0'}, {'category': 'company', 'datetime': 1781043782, 'headline': 'Apple Just Joined the AI Revolution. Investors Could Be in for a Windfall, According to Several Wall Street Analysts.', 'id': 140588201, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Many believed the AI boom had passed Apple by. The company was just biding its time.', 'url': 'https://finnhub.io/api/news?id=5ffc12bdd254d6f66026b62b6bcf9511f64c7faf5cb82a729cbeecfc9cde222f'}, {'category': 'company', 'datetime': 1781043440, 'headline': 'Alphabet’s AI Spend, Waymo Expansion And Search Shifts Weigh On Valuation', 'id': 140588203, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Alphabet (NasdaqGS:GOOGL) agreed to a multi year AI cloud deal with SpaceX, paying US$920 million per month through June 2029 for access to 110,000 Nvidia GPUs. Waymo acquired a 5,500 acre autonomous vehicle testing site in Arizona that was previously used by Apple for self driving development. Google introduced Search profiles, giving publishers and creators dedicated pages in Google Search that may affect how content is discovered and monetized. These moves touch three core areas for...', 'url': 'https://finnhub.io/api/news?id=3f937d8c4e719fdd4b2337bc3df9d6007ca93c195707985a13246691e5fd3b3d'}, {'category': 'company', 'datetime': 1781042874, 'headline': 'S&P 500, Nasdaq End Lower As Investors Take Breather From AI And Chips — AAPL, ASTS, APLD, RIVN, ZVRA In Focus', 'id': 140588210, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'President Donald Trump claims a deal with Iran is just “two or three days” away.', 'url': 'https://finnhub.io/api/news?id=34a7d68cf886e3ee6dc68de76f007d35624f2425aacbabea652c73d586e84ecb'}, {'category': 'company', 'datetime': 1781041257, 'headline': 'Stock Market Today, June 9: Apple Falls as Siri AI Update Raises iPhone Upgrade Questions', 'id': 140586720, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple still needs to show that Siri AI can become a reason to buy a new iPhone, with older-device limits and EU delays shaping the early rollout.', 'url': 'https://finnhub.io/api/news?id=86a5b5323f902cb27188c45f9d70d86898bada13092e4fbfce56406a6e08fffd'}, {'category': 'company', 'datetime': 1781039754, 'headline': 'Stock Market Today, June 9: Risk-Off Sentiment Pressures Nasdaq', 'id': 140586721, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "Tech jitters and profit taking weighed on AI and chip stocks as markets whipsaw and yesterday's apparent rebound falters, today, June 9, 2026.", 'url': 'https://finnhub.io/api/news?id=d4cad48e832ed4dd1914e9bbd6dc3803d143676a14a0978e0b24391d7ebeb6a5'}, {'category': 'company', 'datetime': 1781038899, 'headline': 'Apple Kicks Off WWDC. How to Play AAPL Stock Here.', 'id': 140589924, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple just headed into WWDC 2026 with record earnings, rising AI expectations, and growing pressure to deliver on Apple Intelligence.', 'url': 'https://finnhub.io/api/news?id=1973ac2656a78a0f33c3b2359db5c30c1ecb75fa5d677f9e0e7f7787dcfb952c'}, {'category': 'company', 'datetime': 1781037912, 'headline': 'Nasdaq Composite Falls to 5-Week Low Amid Tech Pullback', 'id': 140586722, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'US equities fell Tuesday, with technology stocks pulling back following a jump in the previous sessi', 'url': 'https://finnhub.io/api/news?id=e95b812179ab657c92a0007fc5d77bc1021ba58bf548a4879e7a9dc9d42b6d5c'}, {'category': 'company', 'datetime': 1781035837, 'headline': 'Nasdaq Slides 250 Points as Chip Stocks Resume Sell-Off: Stock Market Today', 'id': 140588211, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Stocks gave back early gains as geopolitical tensions ramped up and tech stocks sold off.', 'url': 'https://finnhub.io/api/news?id=531bff771cdafa4454581f6b03156c79ade8ef19738ced69a5764ebda23fcb7c'}, {'category': 'company', 'datetime': 1781035470, 'headline': "Apple's iOS 27 Reveals New Clues About $2,000 Foldable iPhone", 'id': 140586723, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Software references and new features suggest Apple is preparing support for a foldable iPhone expected in September.', 'url': 'https://finnhub.io/api/news?id=c4c61d1da8b861213aab3830975355daaebe6d4f3d5afb146445bbc47f574368'}, {'category': 'company', 'datetime': 1781034540, 'headline': 'Rubrik Releases Next Season of Acclaimed "To Catch a Thief" by Nicole Perlroth, Podcast Documentary Details Current Threats from North Korea', 'id': 140584864, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'LAS VEGAS, June 09, 2026--Rubrik FORWARD — Rubrik (NYSE: RBRK), the Security and AI Operations Company, announced the launch of season two of its award-winning documentary podcast, "To Catch a Thief: North Koreans On Our Payroll." Based on exclusive reporting by Nicole Perlroth, bestselling author and former lead cybersecurity reporter for The New York Times, the series exposes a global labor pipeline infiltrated by North Korea—one that is quietly funneling hundreds of millions of dollars a year', 'url': 'https://finnhub.io/api/news?id=4ffb77e665e6e453b3cbb88ce3c9d9738014a2f0166aa058b13c395aaded4774'}, {'category': 'company', 'datetime': 1781033465, 'headline': 'Morgan Stanley Revises Apple Stock Price Target on WWDC Catalyst', 'id': 140584865, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Morgan Stanley Raises Target as AI Push Gains Momentum', 'url': 'https://finnhub.io/api/news?id=a6716e51191f85906d86b16b52b16b71374467ba6ed76333d35b904bb8aa50eb'}, {'category': 'company', 'datetime': 1781033441, 'headline': 'Elon Musk Says He’s Building a Chip “2 to 3 Times” Better Than NVIDIA at 10% The Cost. Is He Bluffing?', 'id': 140584834, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Tesla (NASDAQ:TSLA) CEO Elon Musk dropped a striking claim during a recent conversation with Baron Capital founder Ron Baron, circulated widely after being posted to X by @carm1nee. Musk said he is building a chip that will be “two to three times better than NVIDIA” at 10% of the cost, with a specific focus on ... Elon Musk Says He’s Building a Chip “2 to 3 Times” Better Than NVIDIA at 10% The Cost. Is He Bluffing?', 'url': 'https://finnhub.io/api/news?id=cc839b5857a5b13bb34fc6eec92e9be1c6a725905ab0bb2abe60cdee3e5cf9e1'}, {'category': 'company', 'datetime': 1781033353, 'headline': 'Sector Update: Tech Stocks Fall Late Afternoon', 'id': 140584867, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Tech stocks were lower late Tuesday afternoon, with the State Street Technology Select Sector SPDR E', 'url': 'https://finnhub.io/api/news?id=8b0110014d7f536d83df0eabdb5db4ee53c74d4b0f5a1c2fe4f5780d91980734'}, {'category': 'company', 'datetime': 1781033213, 'headline': 'The only cure for too much supply is lower stock prices, says Jim Cramer', 'id': 140594847, 'image': 'https://image.cnbcfm.com/api/v1/image/108319232-3ED3-MM-A-BLOCK-060926.jpg?v=1781045911&w=1920&h=1080', 'related': 'AAPL', 'source': 'CNBC', 'summary': "'Mad Money' host Jim Cramer talks the state of the tech trade in the current market.", 'url': 'https://finnhub.io/api/news?id=73ea8c2babf99c6844509692620d11c64de1a1774a580e1e2ea452ad99f28caa'}, {'category': 'company', 'datetime': 1781033114, 'headline': 'Elon Musk Just Created $26 Billion a Year for SpaceX Days Before the IPO', 'id': 140584868, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'The market is gearing up for a SpaceX IPO on June 12, and it feels like yesterday that the business confidentially filed for its IPO. That was on April 1 this year. You would expect quiet action since then, but the space-AI hybrid is accelerating before the ticker goes live. SpaceX has signed two monster ... Elon Musk Just Created $26 Billion a Year for SpaceX Days Before the IPO', 'url': 'https://finnhub.io/api/news?id=3f3965b64db5239848583bb68f0b4643a687a8f7e1ad853c6648d93a38fbfc08'}, {'category': 'company', 'datetime': 1781032800, 'headline': 'Apple Left WWDC With More to Prove, Again. Where the Stock Goes From Here.', 'id': 140586724, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': '“Given the level of optimism into this event, we think the announcement came in a bit shy of expectations,” writes TD Cowen analyst Krish Sankar.', 'url': 'https://finnhub.io/api/news?id=cdf34e510cca50ade4de84e5c021672ffab3e587da515b5504e7006f67fedbb6'}, {'category': 'company', 'datetime': 1781032621, 'headline': 'WWDC splits the Mag 7 trade: Apple pressured near term, Alphabet boosted by AI demand', 'id': 140594849, 'image': 'https://image.cnbcfm.com/api/v1/image/108319242-Mac_4_hit.jpg?v=1781046562&w=1920&h=1080', 'related': 'AAPL', 'source': 'CNBC', 'summary': 'CNBC’s MacKenzie Sigalos reports on the divergent market reaction after Apple’s developer conference, as Morgan Stanley raises its Apple price target while investors reward Alphabet’s role in the AI infrastructure stack.', 'url': 'https://finnhub.io/api/news?id=9a4d18f7dcd1065f056fe9bc100e24891af33a32c90f547ca1b77aea8da9c7fe'}, {'category': 'company', 'datetime': 1781032436, 'headline': 'Apple falls after WWDC even as bulls see a longer-term AI upgrade cycle', 'id': 140594850, 'image': 'https://image.cnbcfm.com/api/v1/image/108319164-1781039988929-1781037873-46446440507-hd.jpg?v=1781039960&w=1920&h=1080', 'related': 'AAPL', 'source': 'CNBC', 'summary': 'CNBC’s MacKenzie Sigalos reports on the split reaction to Apple’s developer conference, with shares under pressure despite Morgan Stanley raising its price target and arguing the company’s AI roadmap can still support the next iPhone cycle.', 'url': 'https://finnhub.io/api/news?id=a5707be9036954f21ae6c2f8e19eb498b5997a844f02cbf1c1974d12e606ee92'}, {'category': 'company', 'datetime': 1781032202, 'headline': "Tuesday's session: top gainers and losers in the dow jones index", 'id': 140584418, 'image': 'https://www.chartmill.com/images/uploads/CM_Top_Movers_Small_free_2b4ff2fc22.webp', 'related': 'AAPL', 'source': 'ChartMill', 'summary': "Stay updated with the movements of the dow jones index one hour before the close of the markets on Tuesday. Discover which stocks are leading as top gainers and losers in today's session.", 'url': 'https://finnhub.io/api/news?id=acf87668e27ad9bef18fef1b66745f499e9c8e7c5cddafcffcb8997336d523a5'}, {'category': 'company', 'datetime': 1781031270, 'headline': 'Prominent Tech Investor: ‘When We Were Buying Nvidia in 2023, We Were Paying 4 Times Earnings’', 'id': 140584843, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Alex Sacerdote, founder of Whale Rock Capital, dropped a line on a recent Invest Like the Best episode that stopped listeners cold: “When we were buying Nvidia in 2023, we were paying 4 times earnings. When we bought Tesla in 2019 for the car S-curve, we were paying 5 times earnings. When we were owning ... Prominent Tech Investor: ‘When We Were Buying Nvidia in 2023, We Were Paying 4 Times Earnings’', 'url': 'https://finnhub.io/api/news?id=670e8993a8f56d8c8aef9c805a4bb4049f0d0c916ad0fb0fd435898611cf541b'}, {'category': 'company', 'datetime': 1781029740, 'headline': 'World Cup 2026 Stock Winners: Water Breaks To Boost Fox, US Soccer Could Lift Apple', 'id': 140593649, 'image': 'https://cdn.benzinga.com/files/images/story/2026/06/09/Berlin--Germany---July-09--2006-The-Fifa_3.jpeg?width=2048&height=1536', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'A look at two stocks that could benefit from the 2026 World Cup, especially if Team USA has a strong showing.', 'url': 'https://finnhub.io/api/news?id=fdb6d14953958cc48e982d412c8a2e0abc42a4d29d4b7a638520ceb25c590e17'}, {'category': 'company', 'datetime': 1781029620, 'headline': 'Apple shares slip as analysts offer mixed read on WWDC AI progress', 'id': 140584870, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "Apple Inc (NASDAQ:AAPL, XETRA:APC) shares were down 4% on Tuesday afternoon after the company's annual developer conference left some investors questioning the pace of its artificial intelligence rollout, even as analysts broadly viewed the event as a step forward. At its Worldwide Developers...", 'url': 'https://finnhub.io/api/news?id=c07e5f3efb00ea1c380922e66289449dd12b459975c91700c99160850f3e14a7'}, {'category': 'company', 'datetime': 1781029026, 'headline': 'Equities Markets Fall Intraday Amid Tech Sell-Off', 'id': 140584871, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "Wall Street's benchmark equity indexes fell intraday amid a sharp sell-off in technology stocks, as", 'url': 'https://finnhub.io/api/news?id=352031e99e09b9768017b9c0b84456947c6af5a5c4f5d5bccfafe66fda474990'}, {'category': 'company', 'datetime': 1781028784, 'headline': 'Palantir vs. Apple: Which Stock Offers More Upside in 2026?', 'id': 140584872, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple (NASDAQ: AAPL) and Palantir (NASDAQ: PLTR) both posted their eighth straight EPS beat this spring, but the businesses behind the numbers could not look more different. Apple is selling more iPhone 17 units to a 2.5 billion device installed base. Palantir is signing AI deployment contracts at a pace that doubled its U.S. business. ... Palantir vs. Apple: Which Stock Offers More Upside in 2026?', 'url': 'https://finnhub.io/api/news?id=b55c1cd3fee88455d13240080bd4c33cc99f8f55689557b26e3ff746ff4473eb'}, {'category': 'company', 'datetime': 1781028300, 'headline': 'Which S&P500 stocks are the most active on Tuesday?', 'id': 140583575, 'image': 'https://www.chartmill.com/images/uploads/CM_Most_Active_Stocks_Small_free_fec0650b7f.webp', 'related': 'AAPL', 'source': 'ChartMill', 'summary': "Explore the S&P500 index on Tuesday and find out which stocks are the most active in today's session. Stay updated with the stocks that are capturing market interest.", 'url': 'https://finnhub.io/api/news?id=fc721202adde94c0a97f7c79befcb283435aa8f5effb3c9c9b6f5d9629910171'}, {'category': 'company', 'datetime': 1781026989, 'headline': 'CNBC Markets Now: June 9, 2026', 'id': 140594852, 'image': 'https://image.cnbcfm.com/api/v1/image/108319187-S-MARKETCLOSE-CC-060926.jpg?v=1781040626&w=1920&h=1080', 'related': 'AAPL', 'source': 'CNBC', 'summary': "CNBC Markets Now provides a look at the day's market moves with commentary and analysis from Michael Santoli, CNBC Senior Markets Commentator.", 'url': 'https://finnhub.io/api/news?id=c297ea2b84b9b8b89df2c1d1e863c768c94dd3817a1d610c6274b23b13a30bcf'}, {'category': 'company', 'datetime': 1781026946, 'headline': 'Post Market Wrap: June 9, 2026', 'id': 140594853, 'image': 'https://image.cnbcfm.com/api/v1/image/108319182-S-MARKETCLOSE-CC-060926.jpg?v=1781040563&w=1920&h=1080', 'related': 'AAPL', 'source': 'CNBC', 'summary': 'CNBC brings you fast, accurate, and actionable business news and market updates.', 'url': 'https://finnhub.io/api/news?id=bc537aeec1e4284c17ba8f07a1b3987fd97c352ed2bb6ba1e394026c28c9bc84'}, {'category': 'company', 'datetime': 1781026706, 'headline': 'Where Alphabet Stock Is Most Exposed', 'id': 140584873, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'After a strong run that has left the stock near its high, it’s easy for Alphabet (GOOGL) investors to focus on the rapid growth in AI and the cloud. But with expectations this high, the most important number to watch may not be a growth rate. It’s a measure of profitability that has quietly stretched to a level that warrants a closer look: the net profit margin.', 'url': 'https://finnhub.io/api/news?id=73c2040f349ee7773b7651b836901923622d7a2dfc550f7680675220335ec904'}, {'category': 'company', 'datetime': 1781026359, 'headline': 'Sector Update: Tech Stocks Fall Tuesday Afternoon', 'id': 140583098, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Tech stocks were sharply lower Tuesday afternoon, with the State Street Technology Select Sector SPD', 'url': 'https://finnhub.io/api/news?id=9d581a577ec14d19eb3ca31771a68e72136613ab73ff984b0c8a23d6aa255d89'}, {'category': 'company', 'datetime': 1781026172, 'headline': 'All 30 Dow Jones Stocks Ranked: Buy, Sell or Hold?', 'id': 140584874, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "Nvidia, Visa and Microsoft lead the list of Wall Street's top Dow Jones stocks to buy now. Some other names might surprise you.", 'url': 'https://finnhub.io/api/news?id=1f4c087b2c44ca1cfdcf748e8790b150910bf2efa9437646ea0fda106e6ca111'}, {'category': 'company', 'datetime': 1781025523, 'headline': 'Why Apple Stock Is Sinking Today', 'id': 140583083, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "What does SpaceX's upcoming IPO have to do with Apple stock?", 'url': 'https://finnhub.io/api/news?id=ae1a99bd30acda9435584f2e0532e7336c14a342e1fdd92d9a020a2a108a2840'}, {'category': 'company', 'datetime': 1781025321, 'headline': 'Stock Market Today, June 9: Chipmakers Drag Nasdaq Down at Midday', 'id': 140583100, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "Wall Street reassessed tech leadership as Apple’s AI reveal underwhelmed and yesterday's AI recovery unwound, today, June 9, 2026.", 'url': 'https://finnhub.io/api/news?id=cb5a115921b3d3e104afdc8e3068cd0770cc48a589859548b83cc79a91b2541d'}, {'category': 'company', 'datetime': 1781024840, 'headline': 'Asian stocks track Wall St tech bounce, oil eases on Mideast hope', 'id': 140577233, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "Asian stocks enjoyed a partial rebound from the previous day's rout as investors returned to the AI trade, while easing Middle East tensions also provided support and pushed oil prices down.\xa0Investors also took heart from news that Iran and Israel said Monday they had halted hostilities after exchanging strikes that threatened to reignite the Middle East war.", 'url': 'https://finnhub.io/api/news?id=b05f0b01659f530c29985e5725c24cf3263c529a16472e3562e45504d08ba65d'}, {'category': 'company', 'datetime': 1781024559, 'headline': 'Anthropic Expands Mythos Access After Finding Over 10,000 Serious Vulnerabilities', 'id': 140583102, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'AI cybersecurity model gains 150 new organizations as Anthropic keeps public access restricted.', 'url': 'https://finnhub.io/api/news?id=d950d14189cd1f33932d72d899a70dfb9bb39b5cc0a46b96cc4a6e3939d8cb59'}, {'category': 'company', 'datetime': 1781024458, 'headline': 'Roblox Shares Jump 5.37% After Russia Agencies Seek Ban Reversal', 'id': 140583103, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Russian agencies reportedly asked law enforcement to lift Roblox restrictions after the company pledged compliance with local laws.', 'url': 'https://finnhub.io/api/news?id=850d08c3f142ae1739bf9b1ef624c6e321457aabecf35379feb52fab0f94f830'}, {'category': 'company', 'datetime': 1781024400, 'headline': 'Anthropic launches Mythos-class Claude Fable 5 model, available to the public', 'id': 140583104, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Anthropic has launched Claude Fable 5, its most powerful AI model yet.', 'url': 'https://finnhub.io/api/news?id=c8ea940e7d8e6d0a826af2becf8ad1d59bab494a06f0f9b1e6853ce2ea21fba5'}, {'category': 'company', 'datetime': 1781024370, 'headline': 'Apple quietly reveals how it plans to make money from AI', 'id': 140583105, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Siri Refresh Begins New Subscription Revenue Experiment', 'url': 'https://finnhub.io/api/news?id=569cefb6394f76da91d598e090ae2b22249172fdf33ff2ddfc0f3448ef244d1d'}, {'category': 'company', 'datetime': 1781024297, 'headline': 'Tim Cook Got A Standing Ovation At His Final WWDC, But Do Prediction Markets Appreciate His Message?', 'id': 140587184, 'image': 'https://cdn.benzinga.com/files/images/story/2026/06/09/Apple-Ceo-Tim-Cook-Attends-The-Grand-Ope.jpeg?width=2048&height=1536', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'Apple unveiled its biggest AI overhaul at Tim Cook&#39;s final WWDC, but vague timelines for the Gemini-powered Siri AI sent AAPL stock sliding.', 'url': 'https://finnhub.io/api/news?id=6b00082c934ccb43d36e0cf7dde59c899c750bac8290d5ff9400aa1f59c99cd5'}, {'category': 'company', 'datetime': 1781024170, 'headline': 'Apple WWDC: Can Rebuilt Siri Finally Prove Two-Year AI Vision Pays Off?', 'id': 140583106, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple (NASDAQ:AAPL) finally put its rebuilt Siri on the WWDC stage on Monday, June 8, and the market verdict was swift. The stock spiked 3% during the keynote and flipped negative at the top of the hour, as investors concluded the long-awaited AI reveal landed roughly on par with what Alphabet (NASDAQ:GOOGL) already offers through ... Apple WWDC: Can Rebuilt Siri Finally Prove Two-Year AI Vision Pays Off?', 'url': 'https://finnhub.io/api/news?id=ad90d20c1ba041a58536e3981784441420c2f2a84fad08292036a1679946b433'}, {'category': 'company', 'datetime': 1781023202, 'headline': 'Stay informed with the top movers within the dow jones index on Tuesday.', 'id': 140582052, 'image': 'https://www.chartmill.com/images/uploads/CM_Top_Movers_Small_free_2b4ff2fc22.webp', 'related': 'AAPL', 'source': 'ChartMill', 'summary': "Curious about the top performers within the dow jones index in the middle of the day on Tuesday? Dive into the list of today's session's top gainers and losers for a comprehensive overview.", 'url': 'https://finnhub.io/api/news?id=a42f628a93dc75f3e17052b515f94d3c527d61005ac81f3a1d1e07a3e661dda4'}, {'category': 'company', 'datetime': 1781022780, 'headline': 'Apple announces store closures amid major retail problem', 'id': 140583107, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Just months after temporarily shuttering all its retail stores in the United Arab Emirates amid escalating geopolitical tensions, Apple is making another significant adjustment to its retail footprint, this time in the U.S. The technology giant has confirmed plans to permanently close three Apple ...', 'url': 'https://finnhub.io/api/news?id=eebdcb7c71a7a18c3081ba7a9c8fde050c0ff2d62268ab820b4c7edb91d57851'}, {'category': 'company', 'datetime': 1781022540, 'headline': 'Micron, Marvell, Super Micro, Coherent, Smucker, and More Stocks That Explain Today’s Market', 'id': 140583108, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'The artificial-intelligence trade fizzles out and it appears Monday’s rally might have been a one-off.', 'url': 'https://finnhub.io/api/news?id=e02acf8bc9c09f844ad45c6123d966f214068b2cc54a70713cbee4d3f670661d'}, {'category': 'company', 'datetime': 1781021905, 'headline': 'OpenAI Files For IPO As Market Awaits CPI Data', 'id': 140585973, 'image': '', 'related': 'AAPL', 'source': 'Benzinga', 'summary': '\n\n\n\nAI Excitement\n\n\n', 'url': 'https://finnhub.io/api/news?id=09154b41401ad8a2d63003eb28d10250b8066aac7b6d2928398a5ad3829dc06e'}, {'category': 'company', 'datetime': 1781021752, 'headline': 'Apple: What Will It Take To Win', 'id': 140585398, 'image': 'https://static.seekingalpha.com/cdn/s3/uploads/getty_images/1358389594/image_1358389594.jpg?io=getty-c-w1536', 'related': 'AAPL', 'source': 'SeekingAlpha', 'summary': 'Apple Inc. is rated a Buy post the WWDC and inflation pressure-driven pullback, with the stock testing its EMA50 support line. Read more on AAPL stock here.', 'url': 'https://finnhub.io/api/news?id=3160752683fd9b25b97d1f5e79331e65e7ac6971de1adfdc5632c007876f1b3b'}, {'category': 'company', 'datetime': 1781021354, 'headline': 'It’s not FAANG anymore. It’s MANGOS.', 'id': 140583109, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'With SpaceX, Anthropic, and OpenAI all eyeing massive public debuts, the tech industry may soon have a new class of corporate overlords — and a new acronym to match. Say goodbye to FAANG and hello to MANGOS.', 'url': 'https://finnhub.io/api/news?id=3dd505511da84f337c89146592dd21fa358eecc2dc2ac53c63486b092f6ce2c7'}, {'category': 'company', 'datetime': 1781021059, 'headline': 'Microsoft Stock And The Peril Of Peak Profitability', 'id': 140583110, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'In the race for AI dominance, it’s easy to get lost in the headline numbers: billions in new revenue, exponential growth in users, and a vision for the future that has captivated the market. For Microsoft (MSFT), the story seems compelling. But if you hold the stock, which has underperformed the market with a decline of 11.3% over the past year, your attention should be on a single, less-celebrated figure: the company’s profit margin.', 'url': 'https://finnhub.io/api/news?id=26f34fe97843c4535fa58e8dada720485c171cfb5ae8f07de2a9abc05af02b7e'}, {'category': 'company', 'datetime': 1781020800, 'headline': 'Kiddopia Launches Digital Gift Cards on Amazon’s Online Store', 'id': 140583111, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'WILMINGTON, Del., June 09, 2026--We’re excited to announce that Kiddopia’s subscription digital gift cards are now available in Amazon’s online store. Parents and families can now gift joyful learning experiences with flexible subscription options - including exclusive 3‑month and 6‑month plans available only on Amazon.', 'url': 'https://finnhub.io/api/news?id=021a99e9d7c8464725046ed33dfeb4ff99e9255ff825f93dff8c689c8967c66e'}, {'category': 'company', 'datetime': 1781020201, 'headline': 'What Lit a Fire Under Qualcomm Stock?', 'id': 140583112, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'The chipmaker has been a market laggard for years, so what suddenly convinced investors it was time to get on board.', 'url': 'https://finnhub.io/api/news?id=0443521a63bc2d9330281fd26d8f56d5197c4c35521f1f0cbc765ccb2bc690e3'}, {'category': 'company', 'datetime': 1781020040, 'headline': 'Qualcomm Drops 8% on ByteDance ASIC Deal, Marvell Falls 10% as Custom-Silicon Stocks Slide', 'id': 140581282, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Shares of Qualcomm (NASDAQ:QCOM) are down 8% to $201 in Tuesday morning trading, while Marvell Technology (NASDAQ:MRVL) shares are off 10% to $260. The catalyst centers on news that ByteDance is moving forward with a custom AI silicon (ASIC) deal that touches Qualcomm directly, reshaping the merchant custom-silicon narrative across the sector. The selling action ... Qualcomm Drops 8% on ByteDance ASIC Deal, Marvell Falls 10% as Custom-Silicon Stocks Slide', 'url': 'https://finnhub.io/api/news?id=297d6eeea102c02bb567e23be112d5987d516a9dadca76a063ed2f1004236d82'}, {'category': 'company', 'datetime': 1781019450, 'headline': 'Top Midday Stories: GSK to Acquire Nuvalent for $10.6 Billion in Cash; Apple Introduces Siri AI, But EU Launch to be Delayed', 'id': 140581302, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'The Dow Jones Industrial Average was up, while the S&P 500 and Nasdaq Composite were down in late-mo', 'url': 'https://finnhub.io/api/news?id=ec2c2edf41a7f9677bb886da0f115fa5562a8a2d9ce67bdb11eb526b646b11aa'}, {'category': 'company', 'datetime': 1781019123, 'headline': "Apple is bringing a more 'mainstream' AI to its customers: Analyst", 'id': 140581303, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "Apple (AAPL) showcased its new AI-powered Siri (Siri AI) at its 2026 Worldwide Developers Conference (WWDC), a long-awaited entry into the AI race from the iPhone maker as it offers a more personal style of digital assistant. Creative Strategies CEO and principal analyst Ben Bajarin speaks with Julie Hyman about Apple's strategy to bring AI to the mainstream for its consumers. This was Tim Cook's final WWDC as Apple CEO before he steps down this September, transitioning into an executive chairman role.", 'url': 'https://finnhub.io/api/news?id=ad84af757551a6feea024e61c6729d2fd16b00b85af79d7a4007761517e19847'}, {'category': 'company', 'datetime': 1781018632, 'headline': "Apple's AI News Underwhelms. Siri AI Release Concerns Persist.", 'id': 140581304, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "Apple's AI news failed to excite investors as the consumer electronics giant is seen playing catch-up.", 'url': 'https://finnhub.io/api/news?id=58de39e60106718d814fc6fdbc2307087344a33a9128659d1bd64f289e989df2'}, {'category': 'company', 'datetime': 1781017719, 'headline': "Apple's WWDC 2026 Event Shows 'Clearer' Paths to Monetizing AI, Morgan Stanley Says", 'id': 140581305, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple\'s (AAPL) Worldwide Developers Conference 2026 demonstrated "clearer" paths to monetizing AI so', 'url': 'https://finnhub.io/api/news?id=5d742aeeaa58a353c5093d336415fc1299b2d8296290de461184e1609908d1e0'}, {'category': 'company', 'datetime': 1781016414, 'headline': "Apple may struggle with 'simple' AI narrative in short term", 'id': 140581306, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "Apple (AAPL) kicked off its 2026 Worldwide Developers Conference (WWDC), where CEO Tim Cook showcased the new AI-powered Siri (Siri AI) in his keynote address on Monday. Winthrop Capital CIO Adam Coons comments on Apple's long-awaited AI software release, while Yahoo Finance Markets and Data Editor Jared Blikre takes a closer look at Apple's stock reactions to its WWDC announcements. This was Tim Cook's final WWDC as Apple CEO before he steps down this September, transitioning into an executive chairman role.", 'url': 'https://finnhub.io/api/news?id=8ba185662905ad1edddf3b24187a55bb1a8246ef5790b615e2d88e2f56f954cd'}, {'category': 'company', 'datetime': 1781015324, 'headline': 'Anthropic’s Claude Mythos Launches Today: Crypto Security Shock Ahead?', 'id': 140581307, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Anthropic Mythos launches today as Claude Fable. Discover how this powerful AI could transform crypto security, expose new risks, and reshape blockchain defenses.', 'url': 'https://finnhub.io/api/news?id=811d3107973319efcbbb2b3a8b45d9bf7aae899db1386005293ede886f789d4b'}, {'category': 'company', 'datetime': 1781014150, 'headline': 'Don’t Expect a Boost to iPhone Sales from AI, Analyst Says', 'id': 140581308, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple looks unlikely to spark a big iPhone upgrade cycle with its artificial-intelligence updates, according to Wall Street analysts. UBS analyst David Vogt said he was leaving estimates for Apple’s iPhone revenue in fiscal year 2026 –which ends in September– unchanged at $251.', 'url': 'https://finnhub.io/api/news?id=96101dd770e47f88a329516f3dc9d2ea314f2ee8e11eb9ae229d7ad189c10cce'}, {'category': 'company', 'datetime': 1781014101, 'headline': 'Prediction: Google Stock Will Hit $500 on This Date', 'id': 140581309, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Alphabet (NASDAQ:GOOGL) is running one of the most aggressive AI infrastructure buildouts in corporate history. CEO Sundar Pichai told investors “2026 is off to a terrific start. Our AI investments and full stack approach are lighting up every part of the business.” Google Cloud printed $20.03 billion in Q1 revenue, up 63% YoY, with backlog ... Prediction: Google Stock Will Hit $500 on This Date', 'url': 'https://finnhub.io/api/news?id=5371d7bea6f3b50d20a7a66910495b5a9b96028f78f21e7cc0324ae6e04428ff'}, {'category': 'company', 'datetime': 1781013840, 'headline': 'Apple, Micron, Intel, Applied Digital, Smucker, and More Stocks That Explain Today’s Market', 'id': 140581310, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'There’s no need for Wall Street to worry about the artificial-intelligence trade fizzling out, judging by the stocks rising on Tuesday.  Adding to investors’ AI fervor, OpenAI late Monday reported it has confidentially filed for an initial public offering one week after competitor Anthropic announced it planned to go to market.  Micron Technology  added 2% to $968.53.', 'url': 'https://finnhub.io/api/news?id=c21a80c2667d4fe3117bd122e2b093e5d034b4ea5ea40d1b079969dd81f1e185'}, {'category': 'company', 'datetime': 1781013226, 'headline': 'Siri Didn’t  Rescue Apple', 'id': 140580090, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple’s (NASDAQ: AAPL) new Siri upgrade won’t work in the EU or China for now. China is the world’s largest smartphone market. So, in China, consumers will use old apps on current Apple products. Siri works, supposedly, the way products like OpenAI’s ChatGPT do. Many of its features were teased at the Worldwide Developers Conference, ... Siri Didn’t Rescue Apple', 'url': 'https://finnhub.io/api/news?id=46df794ca980bc47360436a100d36040665c46583ec09a5247fbbdd635e39862'}, {'category': 'company', 'datetime': 1781012124, 'headline': "10 Information Technology Stocks Whale Activity In Today's Session", 'id': 140583619, 'image': 'https://cdn.benzinga.com/files/images/story/2025/11/06/aggregated_options_2.jpg?width=2048&height=1536', 'related': 'AAPL', 'source': 'Benzinga', 'summary': ' ', 'url': 'https://finnhub.io/api/news?id=ba929e11df49d8d9588fd459438f8d16f18a6ad4b9268ac60ccaa7972495c192'}, {'category': 'company', 'datetime': 1781011601, 'headline': 'Apple Just Delivered Its $75 Per Share AI Moment at WWDC. Wall Street Says the Stock Could Hit $440 by Year-End.', 'id': 140580074, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple’s WWDC keynote on June 8 was billed as the most consequential developer conference in the company’s history. From the CNBC Halftime Report broadcasting live from Cupertino, the message from Wall Street was loud: Apple (NASDAQ:AAPL) just delivered the AI moment investors have been waiting two years for, and the upside scenarios now stretch well ... Apple Just Delivered Its $75 Per Share AI Moment at WWDC. Wall Street Says the Stock Could Hit $440 by Year-End.', 'url': 'https://finnhub.io/api/news?id=566fe282a8470568c2c6d11c0eb9d59255ecc7bdefe0f7e69fbab2b5e57b9554'}, {'category': 'company', 'datetime': 1781011412, 'headline': "Apple Stock Falls After WWDC: Analyst Says 'Step In The Right Direction,' But Monetization Questions Remain", 'id': 140585412, 'image': 'https://cdn.benzinga.com/files/images/story/2026/06/09/Cupertino--California--September-25--202_0.jpeg?width=2048&height=1536', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'Apple highlighted its AI products at the 2026 WWDC event. Some analysts are left with questions on the monetization efforts.', 'url': 'https://finnhub.io/api/news?id=852b90e779caa34e5290d59387c3c4e278e96242b9b37378d32ad65a8f0a1ef7'}, {'category': 'company', 'datetime': 1781010736, 'headline': 'Stocks making the biggest moves midday: Apple, Micron Technology, Coherent, DraftKings, J.M. Smucker & more', 'id': 140582168, 'image': 'https://image.cnbcfm.com/api/v1/image/108318273-1780937850054-gettyimages-2279905433-20090101260608-99-669524.jpeg?v=1780937894&w=1920&h=1080', 'related': 'AAPL', 'source': 'CNBC', 'summary': 'Here are the companies making headlines in midday trading.', 'url': 'https://finnhub.io/api/news?id=4bbeca15ca70f638ad1f0f06b76cc9f8fe1256cced9596eaf963e779f884ee7f'}, {'category': 'company', 'datetime': 1781010540, 'headline': 'Tampa Bay Wave Launches 9th Tech|X Accelerator Powered by the Nielsen Foundation, Welcoming 15 Purpose-Driven Founders', 'id': 140580092, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Program alumni have raised $375 million and created 1,600 jobs since 2018; 2026 cohort includes founders from MIT, Harvard, Oxford, and veterans of Apple, Amazon, and Boeing 2026 Tampa Bay Wave Tech|X Accelerator Cohort Tampa Bay Wave welcomes 15 startups to 2026 Tech|X Accelerator Tampa, Fla., June 09, 2026 (GLOBE NEWSWIRE) -- Tampa Bay Wave, Inc. (Wave), a leading nonprofit accelerator and entrepreneurial support organization, is dedicated to fostering groundbreaking technologies and scaling h', 'url': 'https://finnhub.io/api/news?id=5478ebbc5306cd5e80bdc2dc134685f3b9eea17fb7b8f5515096bc0628b45692'}, {'category': 'company', 'datetime': 1781010002, 'headline': 'Apple Inc. (AAPL) is Attracting Investor Attention: Here is What You Should Know', 'id': 140581311, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Recently, Zacks.com users have been paying close attention to Apple (AAPL). This makes it worthwhile to examine what the stock has in store.', 'url': 'https://finnhub.io/api/news?id=81a1db2d4c608b5d00aabb3f0715375456bb6c1686b937999f5bc43d520068b1'}, {'category': 'company', 'datetime': 1781009554, 'headline': 'Apple Delays Siri AI Rollout in EU Following Regulatory Compliance Challenges (AAPL)', 'id': 140580093, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple (NASDAQ:AAPL) will not introduce its new Siri artificial intelligence features in the European Union after failing to satisfy interoperability requirements under the bloc’s regulatory framework, according to comments made Tuesday by a European Commission spokesperson. Speaking to reporters in Brussels, Thomas Regnier said the decision to keep the product out of the EU market was made by Apple itself.', 'url': 'https://finnhub.io/api/news?id=7e7c23052f8c1b79a9defea322ff4ad5b1ff1bf898902763fd652c0589c1c872'}, {'category': 'company', 'datetime': 1781009509, 'headline': 'Stock Market Today: Dow Rises On Trump Comments; Micron, Sandisk Continue To Rebound (Live Coverage)', 'id': 140579674, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Stock Market Today: The Dow Jones index rose Tuesday after Trump said a U.S.-Iran deal could be reached in "two or three days."', 'url': 'https://finnhub.io/api/news?id=ff453183de35dbd3e177e17aeae5069c0a3afea5bf69d0914e6e6481af24f0d2'}, {'category': 'company', 'datetime': 1781008875, 'headline': "Trading the market downturn: The committee's next move", 'id': 140582188, 'image': 'https://image.cnbcfm.com/api/v1/image/108318911-17810219161781021911-46442587073-1080pnbcnews.jpg?v=1781021915&w=1920&h=1080', 'related': 'AAPL', 'source': 'CNBC', 'summary': 'The Investment Committee debate how to trade the losses in the NASDAQ. They reveal their next portfolio moves.', 'url': 'https://finnhub.io/api/news?id=5f779e526f486abc8e952944716a9d87638e347605404014d31b0a89bce51c35'}, {'category': 'company', 'datetime': 1781008869, 'headline': "Tech Stocks' Relief Rally Crumbles: SOXL Craters 15%, AMD Sheds 6% As Recovery Fizzles", 'id': 140582772, 'image': 'https://cdn.benzinga.com/files/images/story/2026/06/09/Close-Up-Of-Stock-Market-Candlestick-Cha.jpeg?width=2048&height=1536', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'The relief rally in tech stocks crumbles on Tuesday, as chip stocks plummet with AMD and SOXL among biggest losers.', 'url': 'https://finnhub.io/api/news?id=2829e7e31a9a006dbc008613c3e294906f632c94daa652d209bcb0425c6fd515'}, {'category': 'company', 'datetime': 1781008253, 'headline': 'Apple Delays AI Tool in EU', 'id': 140580095, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Regulatory requirements force Apple to pause rollout of new Siri features.', 'url': 'https://finnhub.io/api/news?id=760f767685ed6a76a3ffc5b1ab9d1886bf5bbdbc652da67d11f8a4380c0e98e6'}, {'category': 'company', 'datetime': 1781008072, 'headline': "Apple's AI Siri will be held back by aging devices, Morgan Stanley says", 'id': 140580096, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "Apple's newly introduced AI Siri will have limited use across much \u200cof the company's install base because \u200colder iPhones lack the capabilities to run advanced AI \u200bfeatures, Morgan Stanley said in a research note on Tuesday.  More than 850 million iPhones are incapable of running basic Apple Intelligence queries, and \u200cmore than 1.3 \u2060billion iPhones cannot use advanced Siri features, the brokerage said.  The long-delayed Siri \u2060overhaul was the centrepiece of Apple's annual Worldwide Developers Conference on Monday, with the world's \u200bmost valuable \u200bsmartphone maker betting \u200bon the feature to \u200ckeep pace with rivals including OpenAI's ChatGPT, Google's Gemini and Anthropic's Claude.", 'url': 'https://finnhub.io/api/news?id=0ec66f78282f50d2695656a1e9dff65ebb1b0c67803518564734b66e21243e9b'}, {'category': 'company', 'datetime': 1781007660, 'headline': 'Stocks Are Flirting With a Dangerous Valuation Trap', 'id': 140580097, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'What hasn’t really moved, however, is the longer end of the bond market, where yields remain elevated and forecasts for Federal Reserve rate hikes are getting increasingly aggressive following last week’s stronger-than-expected payroll data, and ahead of Wednesday’s May inflation readings.  The higher yields, which have for the most part echoed market bets on a Fed rate hike before the end of the year, now priced at around 70% by the CME Group’s FedWatch, also seem to be resetting at levels that could make stock markets uncomfortable.  Its closest comparison in the bond markets, the yield on 3-month Treasury bills, is holding at around 3.7%.', 'url': 'https://finnhub.io/api/news?id=9dd13a7b915b2df16eb2b5616a0972b454353b22f8ba08055879234a151c6599'}, {'category': 'company', 'datetime': 1781007443, 'headline': 'Why a Passive Income Portfolio With 5 of Warren Buffett’s Highest Yielding Stocks Is Genius', 'id': 140580098, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Warren Buffett stepped down as CEO of Berkshire Hathaway (NYSE: BRK-B) on December 31, 2025, after six decades leading the conglomerate he transformed from a struggling textile mill into a $1 trillion empire. The “Oracle of Omaha” left his successor, Greg Abel, with a very concentrated portfolio: more than 65% of Berkshire’s $381 billion portfolio is ... Why a Passive Income Portfolio With 5 of Warren Buffett’s Highest Yielding Stocks Is Genius', 'url': 'https://finnhub.io/api/news?id=c7a538fb58e7eb96b737ff7f0f3fe48c5a5b2741bba074b1d911143e17565dcc'}, {'category': 'company', 'datetime': 1781007080, 'headline': 'Analysts split on Apple’s WWDC as Siri AI debuts with Google tie-up', 'id': 140580099, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "Investing.com -- Apple's annual Worldwide Developers Conference drew a divided response from Wall Street analysts, with bulls pointing to early monetization signals and a rebuilt Siri while bears questioned whether the updates are enough to drive an upgrade cycle.", 'url': 'https://finnhub.io/api/news?id=4ec1a33d34522a32e3c4cca86949abc81f8f0860095c739fc476bf2385a84e89'}, {'category': 'company', 'datetime': 1781006400, 'headline': "'Apple could be the biggest winner in AI.' Here's why.", 'id': 140580100, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Gerber Kawasaki Wealth and Investment Management CEO Ross Gerber joins Yahoo Finance to explain why Apple (AAPL) has the capacity to effectively win the artificial intelligence (AI) race.', 'url': 'https://finnhub.io/api/news?id=fa5685d8fcfe754a00acb2301e8bb1eab74b53cf27a8d95070f085c0d1ce427f'}, {'category': 'company', 'datetime': 1781004993, 'headline': "Why Apple's WWDC and Siri AI hype left investors sad", 'id': 140579409, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "Apple's stock declined almost 2% on the first day of Apple CEO Tim Cook's final Worldwide Developers Conference (WWDC). The reason was more perceived letdown on the artificial intelligence front, which reawakened chatter that Apple won't dominate in the AI era.", 'url': 'https://finnhub.io/api/news?id=83409c2681f0d9c7d43d77c704dee0a7c0b024e9372c293b76814e33bd19697f'}, {'category': 'company', 'datetime': 1781004523, 'headline': 'Interest Rate Jitters Just Crashed the Tech Rally — Here’s What I’d Lean Toward and What I’d Fade When Yields Spike', 'id': 140579391, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Friday’s bloodbath for the tech and semiconductor stocks might have left a scar on the AI trade, but it might not take all too long for the wounds to heal, especially after an upbeat Monday session that saw semiconductors lead the comeback. Undoubtedly, investors are going to need to make room in their portfolios for ... Interest Rate Jitters Just Crashed the Tech Rally — Here’s What I’d Lean Toward and What I’d Fade When Yields Spike', 'url': 'https://finnhub.io/api/news?id=d9e97b035c52772b95b31d023a6a23177ed59c8ac87c0e98448b2120441452f2'}, {'category': 'company', 'datetime': 1781004416, 'headline': 'Apple shares slide after big Siri AI reveal', 'id': 140582171, 'image': 'https://image.cnbcfm.com/api/v1/image/108318724-1781007139303-gettyimages-2280595110-img_2222.jpeg?v=1781007160&w=1920&h=1080', 'related': 'AAPL', 'source': 'CNBC', 'summary': 'Apple unveiled new artificial intelligence software at WWDC, highlighted by its long-awaited update to Siri.', 'url': 'https://finnhub.io/api/news?id=5ce610f397eaf146372b8bd772d037463359d6e456e5910ed8480775652eadfe'}, {'category': 'company', 'datetime': 1781004360, 'headline': 'I Analyzed the Top Holdings of More Than One Dozen Billionaire Money Managers, and These Are Their 5 Favorite Stocks', 'id': 140579392, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Sustainable moats and the integration of artificial intelligence (AI) are the common denominators for these five businesses.', 'url': 'https://finnhub.io/api/news?id=f59b59be7972db423e892e7f672e994cfcf4fd2cfb7b95f2a80fdb938e0446e1'}, {'category': 'company', 'datetime': 1781003809, 'headline': 'Comparing Apple With Industry Competitors In Technology Hardware, Storage &amp; Peripherals Industry', 'id': 140585414, 'image': 'https://cdn.benzinga.com/files/images/story/2025/11/06/earnings_preview_9.jpg?width=2048&height=1536', 'related': 'AAPL', 'source': 'Benzinga', 'summary': ' ', 'url': 'https://finnhub.io/api/news?id=5482a747973495d35f358981a9188acaf0f78b782b07c00552f5c33460e4faee'}, {'category': 'company', 'datetime': 1781003580, 'headline': 'Nvidia Finally Lands Apple as an AI Customer. Why It Won’t Help the Chip Stock Much.', 'id': 140579395, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Nvidia  was edging up early on Tuesday.  The chip maker has added  Apple  to its roster of big-name customers but details are still scarce on exactly how big a deal it could be.  Nvidia shares were up 0.9% at $210.44 in the premarket.', 'url': 'https://finnhub.io/api/news?id=182565341f2a1c2e5335f6fc670cbb98bcec28f0699814d368afe0b46c2493d3'}, {'category': 'company', 'datetime': 1781003380, 'headline': "36-year-old's fitness company was 'a week away' from bankruptcy—now it's valued at $10.1 billion", 'id': 140582191, 'image': 'https://image.cnbcfm.com/api/v1/image/108317502-1780677523540-WHOOP_SCREENSHOT.png?v=1780677826&w=1920&h=1080', 'related': 'AAPL', 'source': 'CNBC', 'summary': "Whoop was born from founder and CEO Will Ahmed's obsession with tracking his own fitness and recovery as a college athlete.", 'url': 'https://finnhub.io/api/news?id=b08caea46d08021f38b9ba2092d27bb2e3f0371a1942927dae3b48a86cc244af'}, {'category': 'company', 'datetime': 1781003328, 'headline': '143 investors said no to his wearable idea, he says—now Whoop is worth $10.1 billion', 'id': 140582193, 'image': 'https://image.cnbcfm.com/api/v1/image/108316733-WHOOP_SCREENSHOT_2.png?v=1780581342&w=1920&h=1080', 'related': 'AAPL', 'source': 'CNBC', 'summary': 'Will Ahmed founded Whoop at age 22 while he was at Harvard University, with early prototypes developed out of the Harvard Innovation Labs. He was rejected by 143 investors, came within a week of bankruptcy and built a company now valued at $10.1 billion with 2.7 million members across more than 200 countries, he says.', 'url': 'https://finnhub.io/api/news?id=16b786d408693d011b2380b4a2b72fa7deeebb1ad710d12f10a87e34b6f546b4'}, {'category': 'company', 'datetime': 1781002866, 'headline': "Rivian's Momentum Score Surges As EV Maker Says AI Could Make CarPlay, Android Auto Obsolete", 'id': 140580101, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "Rivian Automotive Inc. stock saw a sharp shift in its momentum score, jumping from 17.75 to 73.8 on a week-over-week basis. A momentum score is a metric that evaluates how strongly a stock's price is trending over time by analyzing...", 'url': 'https://finnhub.io/api/news?id=cd36d0102a503e15ca3346601cb80e03752a5c9b57375ca1caa590e4400861d0'}, {'category': 'company', 'datetime': 1781002260, 'headline': 'AI Bulls Are Back in the Driving Seat as Stock Market Sidelines Bubble Fears', 'id': 140579413, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'OpenAI confidentially files IPO paperwork, Apple’s AI reveal, Wall Street likes Lilly over Novo in weight-loss wars, and more news to start your day.', 'url': 'https://finnhub.io/api/news?id=e83e6750be8d264748ffc66df1c5eae0557799cd25392188bcc472d24e892d3f'}, {'category': 'company', 'datetime': 1781002123, 'headline': 'Apple’s AI Push Fails To Impress Wall Street: Analysts Say New AI Features Won’t Spark iPhone Upgrade Cycle', 'id': 140579414, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple presented a host of new AI-related features at its Worldwide Developers Conference post which multiple analysts raised a cautious tone regarding these offerings and its impact on iPhone demand.', 'url': 'https://finnhub.io/api/news?id=d4639944b593657c51d40ebc1e39b2043d100335ab9af9eeca708159566655e8'}, {'category': 'company', 'datetime': 1781001639, 'headline': 'Apple failed to make its AI tool to comply to EU regulations, EU Commission says', 'id': 140579415, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple decided not to roll \u200cout its new Siri \u200cAI tool in the European Union \u200bafter it had unsuccessfully requested to be exempted of interoperability obligations for the tool, a \u200cspokesperson for \u2060the EU Commission said on Tuesday.  "The decision not \u2060to roll out Siri AI in the EU is \u200bApple\'s and \u200bApple\'s \u200bonly," spokesperson Thomas \u200cRegnier told reporters in Brussels.  "Apple was simply unable to develop interoperability solutions that meet essential EU privacy and security \u200cstandards," Regnier said.', 'url': 'https://finnhub.io/api/news?id=ef4eb71eecac10a50239a58042060c6612806635ba29954ab74ee8c903d7affc'}, {'category': 'company', 'datetime': 1781000034, 'headline': 'TD Cowen Maintains Buy on Apple, Raises Price Target to $350', 'id': 140585415, 'image': '', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'TD Cowen  analyst Krish Sankar   maintains Apple (NASDAQ:AAPL) with a Buy and raises the price target from $335 to $350.', 'url': 'https://finnhub.io/api/news?id=316618803b0924bac4368e46cd886474b344196fedda3f97d220c2114ac89062'}, {'category': 'company', 'datetime': 1780999608, 'headline': 'Maxim Group Maintains Buy on Apple, Raises Price Target to $350', 'id': 140585416, 'image': '', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'Maxim Group  analyst Tom Forte   maintains Apple (NASDAQ:AAPL) with a Buy and raises the price target from $310 to $350.', 'url': 'https://finnhub.io/api/news?id=392d242ea3f61be3120b4195599add94a7ca5cb36108aaaf763f80656f66dbec'}, {'category': 'company', 'datetime': 1780997977, 'headline': 'Apple To Rally More Than 19%? Here Are 10 Top Analyst Forecasts For Tuesday', 'id': 140581130, 'image': 'https://cdn.benzinga.com/files/images/story/2026/06/09/Cupertino--California--September-25--202.jpeg?width=2048&height=1536', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'Wall Street analysts change outlook on top names. B of A cuts CPB, UBS cuts AJG PT, B of A boosts ORCL PT, Needham raises APLD PT, Morgan Stanley raises AAPL PT, BTIG raises NRIX PT, GLJ Research raises CLF PT.', 'url': 'https://finnhub.io/api/news?id=24c546043bce2abde755f85fe9addc6d1fe4c18715592924b0caa675be5cc409'}, {'category': 'company', 'datetime': 1780997611, 'headline': '7 Signs Markets Are Near A Top', 'id': 140580009, 'image': 'https://static.seekingalpha.com/cdn/s3/uploads/getty_images/1992892010/image_1992892010.jpg?io=getty-c-w1536', 'related': 'AAPL', 'source': 'SeekingAlpha', 'summary': 'Seven warning signs suggest the stock market may be topping: overbought equities, tech concentration, high valuations, IPO wave and inflation.', 'url': 'https://finnhub.io/api/news?id=97383680109eaed5493bee839ea78653d945845484a8e29d0574b2bd321becfe'}, {'category': 'company', 'datetime': 1780997177, 'headline': 'Market Chatter: SONY Upgrades Struggling Xperia Smartphone With AI Features', 'id': 140578834, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Sony (SONY) will release a new flagship version of its Xperia smartphone on Thursday, adding AI-enab', 'url': 'https://finnhub.io/api/news?id=1d75ad7b4ac920e4e7d59dd802b84ce68c3c7136b353cbc819a46c116d4a69ae'}, {'category': 'company', 'datetime': 1780996446, 'headline': "MANGOS Is The New Magnificent Seven — And Half Of It Hasn't Gone Public Yet", 'id': 140581104, 'image': 'https://cdn.benzinga.com/files/images/story/2026/06/09/AI-generated-MANGOS---EK.jpeg?width=2048&height=1536', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'From FAANG to Mag7 to MANGOS, Wall Street loves its acronyms—each one a barometer of its era.', 'url': 'https://finnhub.io/api/news?id=d272f6002effc36292154b422c30c92756122a0b07397884b0ab02d45d09dfc4'}, {'category': 'company', 'datetime': 1780996031, 'headline': 'Apple Introduces Innovative Features And Intelligence Experiences Across Services; Users Can Enjoy A Richer Flyover On Apple Maps, Get More Flexible Sharing Options On Find My, Easily Split Bills With Apple Cash, And More', 'id': 140585419, 'image': '', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'https://www.apple.com/newsroom/2026/06/apple-unveils-innovative-features-and-intelligence-experiences-across-services/', 'url': 'https://finnhub.io/api/news?id=2af73a7915298ed6076679f32a76eab5a15d465aa954927cc6a00f26974d25a3'}, {'category': 'company', 'datetime': 1780995031, 'headline': 'Rosenblatt Maintains Neutral on Apple, Maintains $276 Price Target', 'id': 140585420, 'image': '', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'Rosenblatt  analyst Barton Crockett   maintains Apple (NASDAQ:AAPL) with a Neutral and maintains $276 price target.', 'url': 'https://finnhub.io/api/news?id=1895a4c08ab5081dc3d642f642b72121e8ad6879f0b20df66c059aa59c11684c'}, {'category': 'company', 'datetime': 1780994950, 'headline': 'Nasdaq, S&P 500 Futures Gain After Tech-Led Rebound: Why NVDA, QCOM, AAPL, APLD, ASTS, NUVL Are Keeping Traders Engaged Today', 'id': 140578822, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Retail sentiment improved. Stocktwits data showed traders continued to maintain a ‘bullish’ stance on SPY and QQQ.', 'url': 'https://finnhub.io/api/news?id=b616d45f6e187964a2a0339e371632e989f1b42c9712b5e893d2cc84d93f51c8'}, {'category': 'company', 'datetime': 1780994622, 'headline': 'Apple Stock Edges Down. What Was ‘Lacking’ in Its Big AI Announcement.', 'id': 140578836, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple shares were edging down early on Tuesday as investors digested its artificial-intelligence plans, which raised some questions among analysts. Apple stock was down 0.3% at $300.74 in premarket trading.', 'url': 'https://finnhub.io/api/news?id=3f525a6b66fa77d224207708d617d2d70115d0ea9782aeb23cb18947b4734153'}, {'category': 'company', 'datetime': 1780993044, 'headline': "Market pullbacks here normal and could provide some opportunities, says Edward Jones' Mona Mahajan", 'id': 140582194, 'image': 'https://image.cnbcfm.com/api/v1/image/108318728-17810071821781007175-46438993323-1080pnbcnews.jpg?v=1781007182&w=1920&h=1080', 'related': 'AAPL', 'source': 'CNBC', 'summary': "Mona Mahajan, Edward Jones head of investment strategy, joins 'Squawk Box' to discuss the latest market trends, state of the economy, where investors can find opportunities right now, and more.", 'url': 'https://finnhub.io/api/news?id=7ed150f8fb9000dd10296f9e1994b059466c4d35de7eb8bceacae3ecfac6ae59'}, {'category': 'company', 'datetime': 1780992458, 'headline': 'Chips Rebound, Intel Catches A $3 Million-Order Tailwind, And OpenAI Joins The IPO Queue', 'id': 140578538, 'image': 'https://www.chartmill.com/images/uploads/THUMBNAILS_CHARTMILL_1000_528_9_7de2be2203.webp', 'related': 'AAPL', 'source': 'ChartMill', 'summary': "Chip names bounced hard after Friday's rout. Intel ripped 11% on a reported Google TPU order. Apple's WWDC underwhelmed. OpenAI filed confidentially for an IPO, adding to the equity supply wall.", 'url': 'https://finnhub.io/api/news?id=4a075424b061ff27fdab9a9e42b338a0a316be08a344feec5c6f94f25769678e'}, {'category': 'company', 'datetime': 1780988397, 'headline': 'Morgan Stanley Maintains Overweight on Apple, Raises Price Target to $360', 'id': 140585421, 'image': '', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'Morgan Stanley  analyst Erik Woodring   maintains Apple (NASDAQ:AAPL) with a Overweight and raises the price target from $330 to $360.', 'url': 'https://finnhub.io/api/news?id=98b696312d3ff4b966b7ffa2d4725cd269fe8fb63fa2e7cb654e0cab1ee8a180'}, {'category': 'company', 'datetime': 1780987916, 'headline': "Wall Street Breakfast Podcast: Siri's Next Act", 'id': 140579179, 'image': 'https://static.seekingalpha.com/cdn/s3/uploads/getty_images/2179888276/image_2179888276.jpg?io=getty-c-w1536', 'related': 'AAPL', 'source': 'SeekingAlpha', 'summary': 'Apple WWDC 2026: New Siri, iOS, and AI updates galore. Sirius XM to join S&P MidCap 400; shares move higher. Costco Wholesale lowers prices on select Kirkland brand items.', 'url': 'https://finnhub.io/api/news?id=7a7892f0e5d2c2f23f563117dfe39088d8413d2a96a1bf0f4b17c9cc2925455b'}, {'category': 'company', 'datetime': 1780986676, 'headline': "Apple's Biggest AI Bet Yet Runs On NVIDIA, Not Its Own Chips", 'id': 140583648, 'image': 'https://cdn.benzinga.com/files/images/story/2026/06/09/Germany---June-26-2024-Apple-Intelligenc.jpeg?width=2048&height=1536', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'Apple WWDC 2026 brings a major Siri AI upgrade, but relies on NVIDIA chips and Google Cloud for its most advanced model.', 'url': 'https://finnhub.io/api/news?id=f49b1fc98e5f02614945b5ed128dbba9761f47e176fad3cfa94956b8ce820a11'}, {'category': 'company', 'datetime': 1780982927, 'headline': "Taiwan Semiconductor Becomes World's Ninth-Most Valuable Company", 'id': 140581105, 'image': 'https://cdn.benzinga.com/files/images/story/2026/06/09/Tokyo--Japan--March-2023-an-Image-Of-Tsm.jpeg?width=2048&height=1536', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'Taiwan Semiconductor cracks the global top 10 as AI demand doubles its value. Get the latest TSM stock update and outlook.', 'url': 'https://finnhub.io/api/news?id=cc25b0da6b8f4d6239ba8bb42723661d9274fe147035358c3c35a8819da30a52'}, {'category': 'company', 'datetime': 1780981200, 'headline': 'Nedap expands partnership with Albert Heijn with mobile access', 'id': 140577753, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Nedap expands partnership with Albert Heijn with mobile access Nedap (AMS:NEDAP), a global leader in Digital Twin Technology and access management solutions, announces the expansion of its partnership with Albert Heijn, with the introduction of Nedap Mobile Access across the offices of Albert Heijn, Etos, Gall & Gall, and Ahold Delhaize in the Netherlands. Groenlo, the Netherlands, 9 June, 2026, 07:00 CEST. Nedap expands partnership with Albert Heijn with mobile access Enabling secure and conven', 'url': 'https://finnhub.io/api/news?id=c85a495e99b2b7034351496c2a517b21876aa198155c0ad9b151679fc060e8e7'}, {'category': 'company', 'datetime': 1780975020, 'headline': 'Apple answers Wall Street’s biggest AI concern', 'id': 140577219, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple is trying to reset the conversation around its place in the artificial intelligence race. The iPhone maker on June 8 unveiled the next generation of Apple Intelligence, including a new and more powerful Siri AI, deeper AI features across its devices, expanded parental controls, and software ...', 'url': 'https://finnhub.io/api/news?id=4ab7f92e678f137fad12996ccb89a05dc8b8d8fa66fc140eee447678f0573de7'}, {'category': 'company', 'datetime': 1780974498, 'headline': 'Why Did AAPL, OSCR, LLY Stocks Hit 52-Week Highs Today?', 'id': 140577220, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple drew investor interest with a major AI update, Oscar Health reaffirmed its outlook, and Eli Lilly further strengthened its position in the weight-loss drug market.', 'url': 'https://finnhub.io/api/news?id=18b62689ad6c41a1d9a445994f027393926db6b7fcc04d4c62658229b5565e7d'}, {'category': 'company', 'datetime': 1780971300, 'headline': 'ValuEngine Weekly Market Summary And Commentary', 'id': 140577886, 'image': 'https://static.seekingalpha.com/cdn/s3/uploads/getty_images/2249691593/image_2249691593.jpg?io=getty-c-w1536', 'related': 'AAPL', 'source': 'SeekingAlpha', 'summary': 'U.S. equity markets moved lower this week, with weakness concentrated in growth and technology-linked areas.', 'url': 'https://finnhub.io/api/news?id=03f78bab5f92598d5453366454323c7f01cd24f091cb881c9fc0e76b03ed04dc'}, {'category': 'company', 'datetime': 1780970208, 'headline': 'Why Apple’s slow-and-steady AI bet is starting to look pretty smart', 'id': 140577221, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "Can Apple's new AI glow up put to bed accusations that it's losing an all-important industry race?", 'url': 'https://finnhub.io/api/news?id=39bc49fe97ef6bf94ba1e6e57ed9b5c1dcbd8e3eb88ecc431cc7ed9fe132c10b'}, {'category': 'company', 'datetime': 1780969873, 'headline': 'These 3 S&P 500 ETFs Are Nearly Identical But After Doing the Math One of Them Saves You Money Over a Lifetime', 'id': 140576667, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Three of the largest U.S. equity index funds on the market look like clones at first glance. Vanguard 500 Index Fund ETF (NYSEARCA:VOO), iShares Core S&P 500 ETF (NYSEARCA:IVV), and Schwab U.S. Large-Cap ETF (NYSEARCA:SCHX) all promise the same thing: cheap, passive exposure to the biggest companies in America. The marketing pitches are nearly indistinguishable. ... These 3 S&P 500 ETFs Are Nearly Identical But After Doing the Math One of Them Saves You Money Over a Lifetime', 'url': 'https://finnhub.io/api/news?id=a109162ae2cab9913183aedae9fa3d9738f203ad8ed626376ac66ea93006121d'}, {'category': 'company', 'datetime': 1780969663, 'headline': "OpenAI's IPO Filing Sparks Reactions From Daniel Newman, Mark Gurman And The Kobeissi Letter — Perplexity CEO Aravind Srinivas Said This", 'id': 140585426, 'image': 'https://cdn.benzinga.com/files/images/story/2026/06/09/Pune--India---February-19--2024--Chatgpt.jpeg?width=2048&height=1536', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'OpenAI&#39;s IPO filing sparked reactions from Daniel Newman, Mark Gurman, The Kobeissi Letter and Aravind Srinivas.', 'url': 'https://finnhub.io/api/news?id=15bfdab38479f95a818256fe05e223300e0238335774c7df5667e0b5badbba71'}, {'category': 'company', 'datetime': 1780969216, 'headline': 'S&P 500, Nasdaq, Dow Futures Slip As Fragile Israel-Iran Truce Faces New Strains: AAPL, APLD, PSKY, GLXY In Focus', 'id': 140577223, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'While Iran and Israel have agreed to halt attacks against each other, the ceasefire between the U.S. and Tehran remains uncertain.', 'url': 'https://finnhub.io/api/news?id=026e583368727b6da0f3a057ceb4762a1fad1b7473a21c85639868bb9e94fa02'}, {'category': 'company', 'datetime': 1780968012, 'headline': "When Will Anthropic Release Mythos? Here's What Prediction Market Is Saying", 'id': 140581107, 'image': 'https://cdn.benzinga.com/files/images/story/2026/06/09/Anthropic-Logo-Is-Displayed-On-A-Smartph.jpeg?width=2048&height=1536', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'Anthropic plans to release its advanced Claude Mythos AI model soon, following the public release of its Claude Opus 4.8 model.', 'url': 'https://finnhub.io/api/news?id=eda83a0a54a57b3224334d566c6373ebd1265f42e03f3f5b5cdd0cc6132a7e20'}, {'category': 'company', 'datetime': 1780964721, 'headline': 'Waymo Snaps Up Apple’s Abandoned Robotaxi Test Track For $220M', 'id': 140576486, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'The deal was recorded on June 5 in Maricopa County official records and reported by TechCrunch.', 'url': 'https://finnhub.io/api/news?id=7e12de2f0562379505d72a40415c97625c64b4667414b4d573029c7e8fe36794'}, {'category': 'company', 'datetime': 1780963328, 'headline': 'Apple Finally Released A Brand-New Siri. Then Its Share Price Cratered.', 'id': 140576480, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple finally pulled the curtain back on its long-awaited AI assistant overhaul today, and Wall Street promptly punished the stock. Apple (NASDAQ:AAPL) unveiled “Siri AI,” a system-wide assistant with on-device context, screen awareness, and a dedicated Siri app, partly powered by Google’s Gemini foundation models. Shares rose 2.5% in early trading, then fell 4.8% after ... Apple Finally Released A Brand-New Siri. Then Its Share Price Cratered.', 'url': 'https://finnhub.io/api/news?id=44d1e6a9ab1381a653b67dc49b2eed6100fbe0ecc824560898f45620c7115138'}, {'category': 'company', 'datetime': 1780961024, 'headline': 'The Real Risk Inside Apple Stock', 'id': 140575545, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "After a powerful run, the biggest vulnerability for one of the world's most valuable companies may be the very thing that made it so successful: its extraordinary profitability.", 'url': 'https://finnhub.io/api/news?id=40ecaeb14b2c7fabb7ca3332f71cb3ba08797e964320116bbe21e91468d16e49'}, {'category': 'company', 'datetime': 1780960687, 'headline': 'Apple’s New Siri AI And Apple Intelligence Put Valuation In Focus', 'id': 140575546, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple unveiled its next generation Siri AI and Apple Intelligence platform at WWDC 2026. The new system focuses on on-device and Private Cloud Compute models with a privacy-first design. Apple also introduced enhanced parental controls aimed at user wellbeing and family usage. For investors watching NasdaqGS:AAPL, this AI update comes with the stock at a share price of $301.54 and a value score of 1. Over the past year, the share price is up 50.3%, and over 5 years it is up 137.1%, which...', 'url': 'https://finnhub.io/api/news?id=95735e02b80a6b724fefc9f29141f41e862be3eff029ee3b0f4849cf8d39a66b'}, {'category': 'company', 'datetime': 1780959990, 'headline': 'S&P 500 and Nasdaq Gain As Chipmaker Stocks Revive, While Israel-Iran Ceasefire Aids Sentiment — AAPL, INTC, AAL, PSKY, CBRS In Focus', 'id': 140576488, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Iran and Israel to pause strikes but warn of retaliation if ceasefire breached.', 'url': 'https://finnhub.io/api/news?id=6d9c34d73c55086b1936cfc7277d1417b8ca89f1a54e2997c49d1edfde553fb6'}, {'category': 'company', 'datetime': 1780958859, 'headline': 'Apple pitches a more personal, easier-to-use AI', 'id': 140575547, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "Apple's pitch for AI is about being personal and easy to use.", 'url': 'https://finnhub.io/api/news?id=84f54d446b2611b60bb8440ccb7404406e3f46d5d081f4d35003853c89a07ac3'}, {'category': 'company', 'datetime': 1780956000, 'headline': "Steve Jobs built Apple and Tim Cook 'expanded' it", 'id': 140575548, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple (AAPL) CEO Tim Cook took the stage on Monday at what will be his final Worldwide Developers Conference (WWDC) keynote speech as chief executive; Cook will be stepping down this September to take on a new role as executive chairman. Geoffrey Cain — the author of "Steve Jobs in Exile" — sits down with Josh Lipton to compare the leadership and achievements of Jobs and Cook.', 'url': 'https://finnhub.io/api/news?id=06a2bcdbdabacea7b7f3fa7f981cdf82666b5708bfe2b3db947fb3cd7481e488'}, {'category': 'company', 'datetime': 1780954901, 'headline': "Apple, SUNation Energy, Tango Therapeutics, Applied Digital And Cerebras Systems: Why These 5 Stocks Are On Investors' Radars Today", 'id': 140581175, 'image': 'https://cdn.benzinga.com/files/images/story/2026/06/08/Hands-Typing-On-A-Keyboard-With-Graphs-A.jpeg?width=2048&height=1536', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'AAPL, SUNE, TNGX, APLD, CBRS were among the stocks seen trending on Monday, June 8, 2026.', 'url': 'https://finnhub.io/api/news?id=09a18cb90762bd92f49afd80fd04daed4defa974c46725e62f43e6f4ebc8e56e'}, {'category': 'company', 'datetime': 1780954150, 'headline': 'Stock Market Today, June 8: Apple Falls After Unveiling AI Siri and Apple Intelligence at WWDC', 'id': 140574138, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Today, June 8, 2026, investors are parsing Apple’s new AI ecosystem push to gauge its impact on future device demand.', 'url': 'https://finnhub.io/api/news?id=3251b1bde0f16a4ce4914d6b0fc742647ea0626aca82783c795fa9bdf5a846b9'}, {'category': 'company', 'datetime': 1780954078, 'headline': 'Apple unveils a more personal kind of Siri AI: WWDC takeaways', 'id': 140574139, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "Apple's (AAPL) annual Worldwide Developers Conference (WWDC) kicks off on Monday at the iPhone maker's headquarters, where the company unveiled its new AI-powered Siri (or Siri AI). Yahoo Finance Tech Editor Dan Howley reports live from Cupertino, CA, to share the biggest takeaways from the 2026 WWDC. This is Tim Cook's final WWDC as Apple CEO before he steps down this September, transitioning into an executive chairman role.", 'url': 'https://finnhub.io/api/news?id=186f3ec442e6d80ba3f5d25e4d5236b610789a58ccb5b2d8ae861fd2b08eb3c4'}, {'category': 'company', 'datetime': 1780953812, 'headline': 'Stock Market Today, June 8: Marvell, Intel, and Micron Lead Tech Stock Rebound', 'id': 140574123, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Marvell’s leap into the S&P 500 caps a sharp AI-chip rebound that helped steady U.S. stocks, today, June 8, 2026.', 'url': 'https://finnhub.io/api/news?id=57fe35c4c3017c208681335866fcc352b9e1db1be78fadae9687ee42123b91ef'}, {'category': 'company', 'datetime': 1780953416, 'headline': 'Dow Jones Futures: Trump, Iran Comments Spark Tech Rebound; Apple, Micron, Nvidia, Sandisk, Tesla Are Big Movers', 'id': 140574127, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "Dow Jones Futures: President Trump and Iran's comments sparked a tech rebound Monday. Micron, Nvidia and Sandisk were big winners.", 'url': 'https://finnhub.io/api/news?id=6c3fe0429fb798eee0f4de5fea5d92ccf0516eff705497606522a269999846e3'}, {'category': 'company', 'datetime': 1780952571, 'headline': 'Apple Delivered AI Siri Today. Investors Yawned—and the Stock Fell.', 'id': 140575549, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Shares of Apple fell close to 2% Monday, sliding while broader markets rose, after the iPhone maker at its annual Worldwide Developers Conference revealed its highly awaited Siri AI along with a slew of other features and its latest operating system', 'url': 'https://finnhub.io/api/news?id=1b1f3684f0bf6cb0ed4ebd4f45389f1f2cfa9b4f56295c2da8903dfdf7b5193e'}, {'category': 'company', 'datetime': 1780952400, 'headline': 'Apple accelerates app development with new intelligence frameworks and advanced tools', 'id': 140574142, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'CUPERTINO, Calif., June 08, 2026--Apple® today introduced new intelligence capabilities, expanded productivity features in Xcode®, and platform improvements that make apps faster, more adaptive, and easier to build.', 'url': 'https://finnhub.io/api/news?id=517643c061c4fcd51ac2d79496eca81f1671d16906f288abafc59fb4e085e7fd'}, {'category': 'company', 'datetime': 1780951996, 'headline': 'Apple WWDC 2026: AAPL Stock Slips As Lack Of Launch Deadline For Siri AI Spooks Retail Investors', 'id': 140574143, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Gene Munster on X, formerly known as Twitter, said AAPL stock is falling because Apple hasn’t given any timeline on the new Siri features.', 'url': 'https://finnhub.io/api/news?id=cb2dbe481209ef0f1784d8d7ee45c551200672691c2e28854262d1d305a9a7e0'}, {'category': 'company', 'datetime': 1780951855, 'headline': 'Waymo bought Apple’s self-driving car proving ground for $220M', 'id': 140574144, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Waymo has acquired a massive 5,500-acre proving ground in Arizona owned by Route 14 Investment Partners LLC, a Delaware shell company associated with Apple, according to documents filed with Maricopa County. Waymo acquired the property, which is located near other proving grounds in Wittman, Arizona, for $220 million, according to the filing. The sale was […]', 'url': 'https://finnhub.io/api/news?id=91454e95fcf43ecceb40a996b57fd510ab38ee4c8334861c336c9e72789d2c28'}, {'category': 'company', 'datetime': 1780951366, 'headline': 'Stock Market Today: Nasdaq Bolts Higher After Iran Halts Strikes; Marvell, Intel Rally (Live Coverage)', 'id': 140568825, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "Stock Market Today: The Dow Jones index rose Monday on Trump's latest Iran comments. Nvidia shows strength while Marvell soars.", 'url': 'https://finnhub.io/api/news?id=54e08c2e88de0caedf2bec2be7a65421b9a20e588a7a72e8565ed7804b44376e'}, {'category': 'company', 'datetime': 1780950177, 'headline': 'Apple Joins AI Race With New Siri Digital Assistant, Apple Intelligence Tools', 'id': 140574146, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple on Monday officially entered the artificial intelligence race by announcing numerous AI innovations.', 'url': 'https://finnhub.io/api/news?id=ef5ae90631411c575065ee22e556db37df006f479390351d51371080bc62cdd2'}, {'category': 'company', 'datetime': 1780949370, 'headline': 'Nasdaq Leads as Chip Stocks Bounce: Stock Market Today', 'id': 140575550, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Semiconductor stocks rebounded sharply on Monday, with Intel and Micron leading chipmakers higher.', 'url': 'https://finnhub.io/api/news?id=02ee03891d5943e48d4884a12821fa51156aa64223c38e663eb766ba5ff537b4'}, {'category': 'company', 'datetime': 1780949094, 'headline': 'Why I Keep Loading Up On This Tech Giant', 'id': 140574147, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'I bought more Apple (NASDAQ:AAPL) last week, and I will probably buy more next month. That has been the rhythm of my portfolio for years now, and the receipts keep telling me to stay the course. When friends ask why I keep adding to a company already worth $4.514 trillion, my answer is short: the ... Why I Keep Loading Up On This Tech Giant', 'url': 'https://finnhub.io/api/news?id=87bde834c0382dc102ef8173dd6a3a51e987dfd38f3c1f40e0923da204c650a2'}, {'category': 'company', 'datetime': 1780948984, 'headline': 'What You Missed About Google Stock Right Before It Went 2x', 'id': 140574148, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Imagine a company outright telling the market that it has way too many customers and not nearly enough capacity to serve them. Having to turn away paying business sounds like a brutal problem.', 'url': 'https://finnhub.io/api/news?id=f9cedfa03d97861d83a4b9eb990bf37a49da308a96a1ecd4711eeea72377cedd'}, {'category': 'company', 'datetime': 1780948325, 'headline': 'Why is this Wealth Manager Buying 1 Million Shares of Harley Davidson?', 'id': 140572424, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Harley-Davidson generates revenue from motorcycle sales and financial services, supported by a global dealer network and iconic brand.', 'url': 'https://finnhub.io/api/news?id=8bb8c024df2383345f78b879b3d90da6a51d7ae9a05e3813ad762aac8618760b'}, {'category': 'company', 'datetime': 1780948092, 'headline': 'Apple Investors Tepid About New AI Platform', 'id': 140574149, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple\xa0investors gave a tepid reception to the next generation of its AI platform. The new Apple Intelligence system, underpinned by\xa0Google technology, was unveiled during a keynote presentation at the company\'s Worldwide Developers Conference. Ed Ludlow reports on "Bloomberg The Close."', 'url': 'https://finnhub.io/api/news?id=2f81f25eb52bcf152c81511fd470a322449edeb080f81c039673cbce8e8b76dd'}, {'category': 'company', 'datetime': 1780947971, 'headline': "Why Apple's AI pivot with new Siri is raising some red flags", 'id': 140572446, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple (AAPL) kicked off its 2026 Worldwide Developers Conference (WWDC) on Monday by showcasing its new AI-powered Siri, dubbed Siri AI. Geoffrey Cain — the author of "Steve Jobs in Exile" — comes on Market Domination to comment on Apple\'s new position on AI and whether that could put pressure to keep up with its Big Tech peers. This is Apple CEO Tim Cook\'s final WWDC keynote as chief executive before he steps down in September and takes on a new role as executive chairman.', 'url': 'https://finnhub.io/api/news?id=9c0afd0cef272320ba093372895c3370ed43e8b217b05b16a4e81364a263aac8'}, {'category': 'company', 'datetime': 1780947723, 'headline': 'SPACEX Heads To Nasdaq — But Steve Eisman Is ‘Not A Fan’ Of The IPO Or Potential Tesla Merger', 'id': 140572447, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Eisman on Monday expressed skepticism about SpaceX potentially merging with EV Giant Tesla Inc (TSLA), highlighting the latter company’s many challenges.', 'url': 'https://finnhub.io/api/news?id=72fc08e9368de0eaf0d3db87f9ffbdf8f2109abccf590e179950d4bdc6a92ead'}, {'category': 'company', 'datetime': 1780947393, 'headline': 'Apple tries again on AI, turns to Google for help', 'id': 140572448, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple unveiled an artificial intelligence overhaul for the iPhone on Monday, turning to Google for help two years after the company stumbled on a first attempt.In the first quarter of this year, Apple iPhone sales grew by double digits in just about every country where it does business.\narp/bgs', 'url': 'https://finnhub.io/api/news?id=346cf7c0a09136dd568f0edd6efcae4a81d691b84e803f06bf8325b5e1fd360b'}, {'category': 'company', 'datetime': 1780946520, 'headline': "Apple's WWDC marks start of AI consumer platform shift, Wedbush says", 'id': 140572449, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple Inc (NASDAQ:AAPL, XETRA:APC) kicked off its annual Worldwide Developers Conference with what Wedbush analysts are calling the beginning of a foundational AI consumer platform shift, as the iPhone maker delivered on promises made two years ago with a more robust artificial intelligence...', 'url': 'https://finnhub.io/api/news?id=85ba221c2a91b57ae281e94b6d6855ff204be783f99f6badf7baef4b752e9cd4'}, {'category': 'company', 'datetime': 1780946283, 'headline': 'Apple: The Wait Was Worth It', 'id': 140575375, 'image': 'https://static.seekingalpha.com/cdn/s3/uploads/getty_images/1705316992/image_1705316992.jpg?io=getty-c-w1536', 'related': 'AAPL', 'source': 'SeekingAlpha', 'summary': 'Apple Inc. is rated a Hold due to valuation concerns and regulatory risks despite optimism on business fundamentals. Learn more about AAPL stock here.', 'url': 'https://finnhub.io/api/news?id=ff8a33b66a23bcadcdfcbe8c7e2eecd338b45e6d875eeff27247ac29fb5f285f'}, {'category': 'company', 'datetime': 1780945802, 'headline': "Exploring the top movers within the dow jones index during today's session.", 'id': 140572134, 'image': 'https://www.chartmill.com/images/uploads/CM_Top_Movers_Small_free_2b4ff2fc22.webp', 'related': 'AAPL', 'source': 'ChartMill', 'summary': "Stay informed about the performance of the dow jones index one hour before the close of the markets on Monday. Uncover the top gainers and losers in today's session for valuable insights.", 'url': 'https://finnhub.io/api/news?id=31059e393c810668d7bec5687df1d98ad5259d646d31695c90e183a11b5037a1'}, {'category': 'company', 'datetime': 1780945248, 'headline': 'Intel Jumps After Reports of Breakthrough Foundry Deals with Google and Nvidia', 'id': 140572439, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Nvidia and Google Spark Intel Rally With Massive Chip Production Moves', 'url': 'https://finnhub.io/api/news?id=d7690e33d7e3f40fc8e315aecbdc77e828a591d28b35b17612c55a2e8fd19b39'}, {'category': 'company', 'datetime': 1780944498, 'headline': 'Trump’s $100,000 H-1B Visa Application Fee Rejected by Judge', 'id': 140572451, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': '(Bloomberg) -- A federal judge struck down a $100,000 fee President Donald Trump ordered for H-1B visa applications, providing a reprieve for US technology companies that rely on hiring skilled foreign workers.Most Read from BloombergHouse Republican Says Hegseth’s D-Day Remarks ‘Inappropriate’LA Mayor Race Flips as Socialist Beats Reality TV Star PrattTrump Says He, Not Congress, Is in Charge of Kennedy Center in ReversalWhy Oil’s Not at $200 After the Biggest Supply Shock in HistoryIsrael Stri', 'url': 'https://finnhub.io/api/news?id=824a32e776c0dc88c77e0427c70e540f2026c8a6df74f9388cd5de0c25909367'}, {'category': 'company', 'datetime': 1780943619, 'headline': 'Apple debuts Siri AI, improved Apple Intelligence as it races to catch rivals', 'id': 140572452, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple unveiled the long-delayed, AI-powered version of its Siri assistant at its WWDC event on Monday.', 'url': 'https://finnhub.io/api/news?id=907e94b81c5784e0443236905be40154027a4ca3a9f172bc75e083d7396e38f1'}, {'category': 'company', 'datetime': 1780943264, 'headline': 'Apple’s ‘Jalen Brunson Moment’? Dan Ives Says WWDC Marks Defining AI Turning Point, Sees Up To $100 Per Share In Upside', 'id': 140572453, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Wedbush analyst Dan Ives says Apple is finally entering the AI game in a meaningful way, creating a new path for services growth that could drive further upside for the stock.', 'url': 'https://finnhub.io/api/news?id=a59f170f5325aecc53dfa6f993f8bdd94dfc18a01b0645c2eeb3dfeb266ec516'}, {'category': 'company', 'datetime': 1780943028, 'headline': 'Tim Cook Ends WWDC With Farewell Message', 'id': 140572454, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple\'s WWDC keynote ended with a farewell message from Tim Cook as he gets ready to step down from his role as CEO. "On a personal note, some of the greatest highlights of my time as CEO have been events like this," Cook said.', 'url': 'https://finnhub.io/api/news?id=b14f26b143585d533799290470d875dd44ad03b794bff9b268f98c698edb6e35'}, {'category': 'company', 'datetime': 1780942380, 'headline': 'Apple introduces Siri AI, a profoundly more capable and personal assistant', 'id': 140572458, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'CUPERTINO, Calif., June 08, 2026--Apple® today introduced Siri® AI, an entirely new version of Siri, powered by Apple Intelligence™. A profoundly more capable and conversational assistant with personal context understanding, broad world knowledge, and onscreen awareness, Siri AI can help users find what they need in the moment, from answering questions from the web on virtually any topic, to surfacing relevant information from a user’s personal messages, emails, photos, and more. Siri AI also in', 'url': 'https://finnhub.io/api/news?id=ef9aab75496f87ab1888a769ccc68cd25e063039ccfe687832404d88c465029c'}, {'category': 'company', 'datetime': 1780942380, 'headline': 'WWDC26: Apple unveils next generation of Apple Intelligence, Siri AI, powerful parental controls, and an expansive set of software improvements', 'id': 140572457, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'CUPERTINO, Calif., June 08, 2026--Today, during the Worldwide Developers Conference, Apple® previewed its upcoming software releases that will deliver the next generation of Apple Intelligence™ and introduce Siri® AI, an entirely new version of Siri that is profoundly more intelligent, knowledgeable, and capable. The releases also bring powerful and intuitive new features to help parents create safe digital experiences for kids, as well as improvements that further elevate the software design an', 'url': 'https://finnhub.io/api/news?id=5dad6b8a40e57f2568dec6f7a45e130ce55663e2ac410776074e934685fe6b3a'}, {'category': 'company', 'datetime': 1780942380, 'headline': 'Apple previews new child safety features', 'id': 140572456, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'CUPERTINO, Calif., June 08, 2026--Apple® today previewed a new suite of powerful, intuitive, and easy-to-use features designed to allow parents to more easily manage the content their children can see, who they can communicate with, and when they have access to apps. With software updates this fall, parents will be able to access new child safety features, including a simpler setup experience with a recommended set of essential apps, Ask to Browse, Time Allowances, and a redesigned Screen Time.', 'url': 'https://finnhub.io/api/news?id=cff71e218a31e3ec08c16a44de4aa04ccb9a423ebd9f4f3685bdd89159017ec0'}, {'category': 'company', 'datetime': 1780942380, 'headline': 'Apple Intelligence brings powerful AI capabilities into everyday experiences', 'id': 140572455, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'CUPERTINO, Calif., June 08, 2026--Apple® today introduced the next generation of Apple Intelligence™, powered by a bold new architecture that integrates the latest Apple Foundation Models deep into Apple’s platforms and is uniquely designed to protect users’ privacy. This makes the apps and experiences users rely on every day across iPhone®, iPad®, Mac®, Apple Watch®, AirPods®, and Apple Vision Pro® more personal and helpful than ever. Apps become smarter and more useful with powerful editing ca', 'url': 'https://finnhub.io/api/news?id=e9d9b9365b70da648d1c8ec95e2510ad34ae57072db90b96662866845ec74d08'}, {'category': 'company', 'datetime': 1780942233, 'headline': 'Apple Stock Turns Negative After AI Updates', 'id': 140572459, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "Apple stock slipped into negative territory on Monday as Wall Street seemed underwhelmed by the company's artificial intelligence updates. Shares were down 1% to $304.42 about an hour into the WWDC keynote.", 'url': 'https://finnhub.io/api/news?id=09d3811ded3025c4b9d1076d81646576d6b88de75a265413171d69585a11e03a'}, {'category': 'company', 'datetime': 1780941900, 'headline': "Curious about the most active S&P500 stocks in today's session?", 'id': 140571396, 'image': 'https://www.chartmill.com/images/uploads/CM_Most_Active_Stocks_Small_free_fec0650b7f.webp', 'related': 'AAPL', 'source': 'ChartMill', 'summary': "Looking for the most active S&P500 stocks in today's session? Join us as we dive into the US markets on Monday and discover the stocks that are dominating the trading activity and setting the pace for the market.", 'url': 'https://finnhub.io/api/news?id=a965db2c66c4eb3b53ff40817e32ba34b46c6c17628acb63ecf03b12fa49605c'}, {'category': 'company', 'datetime': 1780940792, 'headline': 'Siri AI Updates Are Here and Apple Stock Is Falling', 'id': 140572460, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Siri is becoming a more capable AI assistant, and a key issue that Wall Street has been waiting to see.  Apple showed off an updated Siri that can answer specific questions better than before while also taking actions on behalf of the user.  In a demo at WWDC, an executive asked Siri to take certain actions, like finding specific photos and adding them to an album, setting calendar reminders, and more.', 'url': 'https://finnhub.io/api/news?id=f4ff40a82e86b8fb88fa0f9dd38ddbbff3ddf996760562e42178c2b7c30aec65'}, {'category': 'company', 'datetime': 1780940646, 'headline': 'Apple makes trust and safety push for the iPhone via iOS 27', 'id': 140572461, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple debuted its iOS 27 at its annual developer conference on Monday.', 'url': 'https://finnhub.io/api/news?id=d6d4108522de47cf33003b5035638b6be3ba8d68d8e222a11fac744e5a215419'}, {'category': 'company', 'datetime': 1780940317, 'headline': "Intel's Stock Is Soaring. Hopes of Chipmaking Deals With Google and Nvidia Are Lifting the Shares.", 'id': 140572462, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Intel shares soared Monday following a report of a new chipmaking deal with Google and the possibility of another with Nvidia on the way.', 'url': 'https://finnhub.io/api/news?id=1234af9a90ea67484c656ccf14010968341f883e58538614aa47e1df2325e20d'}, {'category': 'company', 'datetime': 1780939189, 'headline': 'Dear Apple Stock Fans, Mark Your Calendars for June 8', 'id': 140570687, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple Eyes AI Breakthrough as Investors Await WWDC Catalyst', 'url': 'https://finnhub.io/api/news?id=521c3b1e3cab94b7694d9191cc8a72fb32386558b6185e6b9be1d8cbb69f8f3c'}, {'category': 'company', 'datetime': 1780938851, 'headline': 'Apple Introduces New AI Integration APIs And Expanded Agentic Coding Tools In Xcode 27, Enhancing App Development With Advanced Intelligence Capabilities And Platform Improvements', 'id': 140585431, 'image': '', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'New APIs for integrating AI models and extended agentic coding in Xcode 27 provide developers with powerful new ways to build and refine their appsApple® today introduced new intelligence capabilities, expanded', 'url': 'https://finnhub.io/api/news?id=6668a4539a35f8a02cafe1da447eb554a00f6e76f2822f010beaa2df7c9dc55d'}, {'category': 'company', 'datetime': 1780938420, 'headline': 'Micron, Intel, Tesla, Apple, Lilly, and More Stocks That Explain Today’s Market', 'id': 140570692, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'The brutal AI selloff that rocked the market on Friday may end up being short-lived, judging by how chip makers are trading Monday.', 'url': 'https://finnhub.io/api/news?id=4d110ee2d8af81749f088eca00f7a4dc8fbb9e50b1035fd6bf6efd2a2131d0c1'}, {'category': 'company', 'datetime': 1780937707, 'headline': "As Apple's WWDC conference kicks off, investors want to know if AI will save Siri", 'id': 140570688, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple on Monday will test its standing in the AI race as executives kicked off its developer conference, with the company expected to showcase a long-awaited Siri overhaul and tools to tap the computing power of its 2.5 billion devices.  Apple CEO Tim \u200cCook launched the company\'s annual Worldwide Developers Conference by saying the day\'s announcements will center on Apple Intelligence and Siri.  Apple\'s new iOS 27 operating system will extend back to iPhone 11 models, the company said, \u200badding that the next version of its MacOS will be called "Golden Gate."', 'url': 'https://finnhub.io/api/news?id=289c5070f1757b0b455764002b6eb216539fdb1f5e3f0c065bee5b90fe550caa'}, {'category': 'company', 'datetime': 1780937608, 'headline': 'As Changing Fed Expectations Rattle Tech Stocks, This Cash-Generating Titan Is The Clear Winner', 'id': 140570669, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Micron Technology (NASDAQ:MU) is the stock everyone wants to talk about right now, with shares up 202.87% year to date on an AI memory supercycle narrative that has order books reportedly stretching into 2027. But here’s what you should actually be watching. The Crowded Trade At The Top Of Its Cycle Micron just reported a ... As Changing Fed Expectations Rattle Tech Stocks, This Cash-Generating Titan Is The Clear Winner', 'url': 'https://finnhub.io/api/news?id=e2c9792dd37c68e28be7c979c7215a31f8d24ad9721b0346691cb0efdf53fbae'}, {'category': 'company', 'datetime': 1780936802, 'headline': "Uncover the latest developments among dow jones stocks in today's session.", 'id': 140569745, 'image': 'https://www.chartmill.com/images/uploads/CM_Top_Movers_Small_free_2b4ff2fc22.webp', 'related': 'AAPL', 'source': 'ChartMill', 'summary': "Get insights into the dow jones index performance on Monday. Explore the top gainers and losers within the dow jones index in today's session.", 'url': 'https://finnhub.io/api/news?id=8c8257dc9c69632011b8062e3a77a81c1b77ef6d1569d0dadb8eced14e6490a6'}, {'category': 'company', 'datetime': 1780934429, 'headline': "Siri update, AI take center stage at Apple's WWDC", 'id': 140570690, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "Yahoo Finance Tech Editor Dan Howley joins Market Catalysts from Apple's (AAPL) annual Worldwide Developers Conference (WWDC) at its Cupertino, Calif., headquarters as the 2026 event kicks off.", 'url': 'https://finnhub.io/api/news?id=0a0a2b9c83dee8fad9d880e9738575603037fafd1c196fcd5ec82a5109384e7a'}, {'category': 'company', 'datetime': 1780933653, 'headline': "Buy The Dip? Not So Fast. 6 Stocks Investors Ignored In Last Week's Chaos", 'id': 140575306, 'image': 'https://cdn.benzinga.com/files/images/story/2026/06/08/retail-traders---EK.jpeg?width=2048&height=1536', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'The biggest names weren&#39;t bought as much as expected when tech stocks bombed last Friday.', 'url': 'https://finnhub.io/api/news?id=e2eec2d13edbc3c62b92db508815ce3ce4674461ff4b706ed938c8078c46cc4d'}, {'category': 'company', 'datetime': 1780933293, 'headline': 'Apple At The Bottom Of The Big Tech Barrel', 'id': 140570691, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'The Wall Street Journal publishes a widely followed list each year called “The Best Companies For the Future.” Compiled with Bendable Labs, it uses’AI readiness, innovation, talent readiness, financial fitness, resilience, and agility.’ The major megacap tech companies are at the very top. Apple (NASDAQ: AAPL) is down the list, barely above S&P Global, which ... Apple At The Bottom Of The Big Tech Barrel', 'url': 'https://finnhub.io/api/news?id=cd2bcd2298c78ff7a7c79e43032d2e18e73d02477ee62c74f1e619b50d41583b'}, {'category': 'company', 'datetime': 1780932600, 'headline': "AI is 'not existential' to Apple as it is for rest of Silicon Valley", 'id': 140568844, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple (AAPL) is kicking off its annual Worldwide Developers Conference on Monday in Cupertino, CA. While investors and iPhone customers will be tuning in this week to hear the newest features for Apple devices, will AI be one of them? Morning Brief Host Julie Hyman and Barron\'s Investor Circle Newsletter editor Josh Schafer discuss Apple\'s lack of an "AI problem" as its Big Tech peers rush to adopt the technology.', 'url': 'https://finnhub.io/api/news?id=c8f4b6cc9420abf6bb0e34ddfc24d0000acff5085875d206eb1cc828940edbcd'}, {'category': 'company', 'datetime': 1780932248, 'headline': "Apple Exec, At WWDC, Says Apple Has Built Its Own World Knowledge Service That Runs In Its Private Cloud Compute Platform; Apple Worked With Google And NVIDIA To Bring Its Private Cloud Compute Approach To Google Infrastructure In Google Cloud; Apple's Four Other Models Aside From AFM Cloud Pro Will Continue To Run On Apple Silicon", 'id': 140572611, 'image': '', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'https://www.apple.com/apple-events/event-stream/', 'url': 'https://finnhub.io/api/news?id=1b318ab0d8c881859a353f73a2391e1f8e129177e3b88ad49426beb6510235f7'}, {'category': 'company', 'datetime': 1780932018, 'headline': "Apple Software Chief Craig Federighi, On New Apple Intelligence Features, Says We Do Not Use Google Search As The Basis Of Our System; Many Apple Intelligence Requests Are Processed On Device, More Complex Requests Sent To Apple's Own Private Cloud Compute; Apple's Private Cloud Will Use Three Apple Owned AI Models Made Through Its Work With Google", 'id': 140584197, 'image': '', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'https://www.apple.com/apple-events/event-stream/', 'url': 'https://finnhub.io/api/news?id=99b9005aec2bf15713f1dcb99b8f56d2b12d47b90e5e2e1c46e9d9ac6a61103f'}, {'category': 'company', 'datetime': 1780931997, 'headline': 'Is Apple Inc. (AAPL) A Good Stock To Buy Now?', 'id': 140568845, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Is AAPL a good stock to buy? We came across a bullish thesis on Apple Inc. on X.com by @MoneyShow. In this article, we will summarize the bulls’ thesis on AAPL. Apple Inc.’s share was trading at $307.34 as of June 5th. AAPL’s trailing and forward P/E were 37.21 and 32.15 respectively according to Yahoo Finance. Apple […]', 'url': 'https://finnhub.io/api/news?id=7be9a3b5fec2ab233f1a22887741af746eb64c1bd422cc03cb85f35eda5bf707'}, {'category': 'company', 'datetime': 1780931911, 'headline': "Apple's Revamped AI Smashes Against Down Market", 'id': 140568846, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "Expectations are running high for Apple's\xa0Worldwide Developers Conference, where the company is expected later Monday to unveil the biggest overhaul of Siri in years, including a\xa0chatbot-style interface\xa0and deeper integration across the iPhone, iPad and Mac. Bloomberg Tech co-Host Ed Ludlow discusses his expectations for the conference and how developments in Siri could impact the rest of the AI space. He also addresses investor expectations for the upcoming SpaceX IPO.", 'url': 'https://finnhub.io/api/news?id=ba4e44d045056d7a9f1b6c2da7983791f5ff757a0d94b706dead9faf635ad5a9'}, {'category': 'company', 'datetime': 1780931670, 'headline': "Apple Stock Is Sliding Today: What's Going On?", 'id': 140585435, 'image': 'https://cdn.benzinga.com/files/images/story/2026/06/08/Apples-New-Iphone-18-Pro-Presentation-On_0.jpeg?width=2048&height=1536', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'Apple Inc (NASDAQ: AAPL) shares hit fresh record highs early Monday before fading as investors digested WWDC 2026 announcements.', 'url': 'https://finnhub.io/api/news?id=bcfaad52085fc3872f977fac3344248617ff4f09d452742d4624100d879ad897'}, {'category': 'company', 'datetime': 1780931416, 'headline': "Tim Cook Will Start His Last WWDC the Way He Always Does. 'Good Morning.'", 'id': 140570693, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "This is Tim Cook's last WWDC, and Apple's CEO will kick things off just like he always has.  Cook is stepping down in September after 15 years as the iPhone maker's top leader.  Early Monday, Cook took a trip down memory lane of sorts.", 'url': 'https://finnhub.io/api/news?id=211142f74b98e3a03e648c6f3f66e4405d45a781e4514309edade5ef74198a78'}, {'category': 'company', 'datetime': 1780930867, 'headline': "Apple's AI Ambition Has A Picks-and-Shovels Trade —  Here's Who Could Win", 'id': 140572602, 'image': 'https://cdn.benzinga.com/files/images/story/2026/06/08/Close-up-Image-Of-The.jpeg?width=2048&height=1536', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'Apple&#39;s AI ambitions may lead to gains for suppliers like TSMC, Broadcom, Arm, Corning and more.', 'url': 'https://finnhub.io/api/news?id=6265a094065ec914967ae0d9406a4b7b04eca67e8b59a4fa9fac4835db4c5d3d'}, {'category': 'company', 'datetime': 1780930620, 'headline': 'Week ahead: SpaceX readies for liftoff as inflation clouds gather', 'id': 140568847, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "Wall Street heads into a big week after a sharp selloff rattled investors, with inflation data, Apple's annual developer conference and the highly anticipated SpaceX initial public offering set to dominate market attention. Stocks ended last week under pressure after a stronger-than-expected...", 'url': 'https://finnhub.io/api/news?id=93650f8a19b4f059b35b36ed27c662fec54f1c72e023e291e8208445e4606bab'}, {'category': 'company', 'datetime': 1780929600, 'headline': 'Peer To Peer Network Submits MOBICARD(TM) 1.8 To Apple App Store And Google Play Store Will Follow', 'id': 140568848, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'MobiCard™ 1.8 Introduces Enhanced User Experience, News Feed Functionality, Enterprise Advertising, Paid Individual Accounts, Audio Messaging, and Expanded Analytics CAMBRIDGE, MA / ACCESS Newswire / June 8, 2026 / Peer To Peer Network, Inc. ...', 'url': 'https://finnhub.io/api/news?id=06a6f66885ce724dc39910fadf816407d846cefd8c6e887e4891f7110de29b8b'}, {'category': 'company', 'datetime': 1780928055, 'headline': 'Apple Stock Rises Ahead of WWDC', 'id': 140568849, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'Apple stock was higher Monday morning as Wall Street waited for the Worldwide Developers Conference to begin. Shares were rising 1.1% to $310.84. The stock has now gained 15% this year and 55% over the past 12 months.', 'url': 'https://finnhub.io/api/news?id=08e539c835276689ff84102280d387e13efb21f424cd166ed09c23ba249f07e7'}, {'category': 'company', 'datetime': 1780927958, 'headline': 'Apple WWDC Keynote: Siri AI Will Not Be Available In China As Apple Works Through Regulatory Issues', 'id': 140571800, 'image': '', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'https://www.apple.com/apple-events/event-stream/?useASL=true', 'url': 'https://finnhub.io/api/news?id=a872df3e977891364cd4ce77ea3ad2fe7a3e5516bd1ebe398eada4fbdb4f0f99'}, {'category': 'company', 'datetime': 1780926736, 'headline': "Nvidia CEO's Comments Trigger Buying In AI Stocks; High Hopes For Apple AI", 'id': 140572613, 'image': '', 'related': 'AAPL', 'source': 'Benzinga', 'summary': '\n\n\n\nNvidia CEO Talks His Book\n\n\n', 'url': 'https://finnhub.io/api/news?id=bd3dec8cc271ae0353613987aff30359511dc2cadb88d84ff4f163e2fbf021c1'}, {'category': 'company', 'datetime': 1780926500, 'headline': 'Apple WWDC Keynote: Tailoring Siri AI For WatchOS', 'id': 140585439, 'image': '', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'https://www.apple.com/apple-events/event-stream/?useASL=true', 'url': 'https://finnhub.io/api/news?id=3e0cee98ffb3af4361d23d26f9f5a20428938994fec367b6560fa0f1840f252f'}, {'category': 'company', 'datetime': 1780926006, 'headline': 'Apple WWDC Keynote: Siri Improvements Extend To CarPlay And AirPods', 'id': 140585440, 'image': '', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'https://www.apple.com/apple-events/event-stream/', 'url': 'https://finnhub.io/api/news?id=493935313f5de5289d4d4437a4d6b640d2f831dd9d0227323b85e3d3c2a8bbd3'}, {'category': 'company', 'datetime': 1780925820, 'headline': "Markets Rebounding After Friday's Rout", 'id': 140570601, 'image': 'https://static.seekingalpha.com/cdn/s3/uploads/getty_images/2250910149/image_2250910149.jpg?io=getty-c-w1536', 'related': 'AAPL', 'source': 'SeekingAlpha', 'summary': 'The markets look like they are in recovery mode after Fridayâ\x80\x99s hit, buoyed somewhat by S&P 500â\x80\x99s rebalancing moves, which are officially effective in two weeks.', 'url': 'https://finnhub.io/api/news?id=858876fe33f3ac481ce2edfd8070bdac5996aa439e214cfa28f7c0588e189362'}, {'category': 'company', 'datetime': 1780925729, 'headline': 'Apple WWDC Keynote: Introducing An Entirely New Version Of Siri Unlocked By Apple Intelligence', 'id': 140585441, 'image': '', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'https://www.apple.com/apple-events/event-stream/', 'url': 'https://finnhub.io/api/news?id=a1241b0dd15960041b3d900f68fdac068a022432b3193d5fe017f745a11cc099'}, {'category': 'company', 'datetime': 1780924472, 'headline': 'Apple WWDC Keynote: Apple Devices Will Have Search Index For On-Device Content', 'id': 140585442, 'image': '', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'https://www.apple.com/apple-events/event-stream/', 'url': 'https://finnhub.io/api/news?id=3263d21acfa4fef1ea9de5f34904ae20a4f54563524d0bed4400e298d27f4b6d'}, {'category': 'company', 'datetime': 1780924356, 'headline': 'Apple WWDC Keynote:  iOS 27 Will Extend Back To iPhone 11 Models', 'id': 140585443, 'image': '', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'https://www.apple.com/apple-events/event-stream/', 'url': 'https://finnhub.io/api/news?id=21ef143b418b971796a13b04c35d1937ae600618a5d1d48a3418bbcf37612557'}, {'category': 'company', 'datetime': 1780924324, 'headline': '5 of the Best Stocks Warren Buffett Has Ever Purchased', 'id': 140567657, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': "When it comes to Buffett's stock picks, a few stand out as particularly prescient. Here's a list of the former Berkshire CEO's best stock purchases.", 'url': 'https://finnhub.io/api/news?id=a64782ed2a450c19c215490d72701bae8303ce19566e6852c45fd6a51efdba87'}, {'category': 'company', 'datetime': 1780924205, 'headline': 'Apple WWDC Keynote: Integrating Additional Layers Of Liquid Glass Directly Into App Icon Artwork Itself', 'id': 140585444, 'image': '', 'related': 'AAPL', 'source': 'Benzinga', 'summary': 'https://www.apple.com/apple-events/event-stream/', 'url': 'https://finnhub.io/api/news?id=6d80eaadf83b1d17bcdaa49166a4956ca3705b5a1bf588ffea8a4bf7307677a2'}, {'category': 'company', 'datetime': 1780924070, 'headline': 'Apple knows it has a Siri problem. It’s about to fix it', 'id': 140567658, 'image': 'https://s.yimg.com/rz/stage/p/yahoo_finance_en-US_h_p_finance_2.png', 'related': 'AAPL', 'source': 'Yahoo', 'summary': 'During its Worldwide Developers Conference, Apple is expected to announce a new version of Siri that could help it catch up in the AI race.', 'url': 'https://finnhub.io/api/news?id=b59566ec8ef75a64a6792f37ce8b7d7137eb3c623193be2c0274b79de838092c'}]